<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>Modèles mixtes</title>

<script src="libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="libs/bootstrap-3.3.5/css/spacelab.min.css" rel="stylesheet" />
<script src="libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="libs/navigation-1.1/tabsets.js"></script>
<link href="libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>



<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Modèles mixtes</h1>
<h4 class="date"><em>21 novembre 2018</em></h4>

</div>


<div id="effet-de-lazote-sur-le-rendement-de-varietes-davoine" class="section level2">
<h2>1. Effet de l’azote sur le rendement de variétés d’avoine</h2>
<p>Le tableau de données <code>Oats</code> inclus dans le package <em>nlme</em> présente les résultats d’une expérience agricole en parcelles divisées (<em>split-plot</em>). L’expérience est réalisée en six blocs (<code>Block</code>). Chaque bloc est divisé en trois sections où une variété différente d’avoine est semée (<code>Variety</code>), puis chaque section est divisée en quatre quadrants qui reçoivent chacun une concentration différente d’azote (<code>nitro</code>): 0, 0.2, 0.4 ou 0.6. La variable réponse est le rendement (<code>yield</code>) en avoine pour chacun des 72 quadrants (6 blocs x 3 variétés x 4 concentrations d’azote).</p>
<pre class="r"><code>library(nlme)
data(Oats)
# Changer le bloc en facteur non-ordonné
Oats$Block &lt;- factor(Oats$Block, ordered = FALSE)
str(Oats)</code></pre>
<pre><code>## Classes &#39;nfnGroupedData&#39;, &#39;nfGroupedData&#39;, &#39;groupedData&#39; and &#39;data.frame&#39;:   72 obs. of  4 variables:
##  $ Block  : Factor w/ 6 levels &quot;VI&quot;,&quot;V&quot;,&quot;III&quot;,..: 6 6 6 6 6 6 6 6 6 6 ...
##  $ Variety: Factor w/ 3 levels &quot;Golden Rain&quot;,..: 3 3 3 3 1 1 1 1 2 2 ...
##  $ nitro  : num  0 0.2 0.4 0.6 0 0.2 0.4 0.6 0 0.2 ...
##  $ yield  : num  111 130 157 174 117 114 161 141 105 140 ...
##  - attr(*, &quot;formula&quot;)=Class &#39;formula&#39;  language yield ~ nitro | Block
##   .. ..- attr(*, &quot;.Environment&quot;)=&lt;environment: R_GlobalEnv&gt; 
##  - attr(*, &quot;labels&quot;)=List of 2
##   ..$ y: chr &quot;Yield&quot;
##   ..$ x: chr &quot;Nitrogen concentration&quot;
##  - attr(*, &quot;units&quot;)=List of 2
##   ..$ y: chr &quot;(bushels/acre)&quot;
##   ..$ x: chr &quot;(cwt/acre)&quot;
##  - attr(*, &quot;inner&quot;)=Class &#39;formula&#39;  language ~Variety
##   .. ..- attr(*, &quot;.Environment&quot;)=&lt;environment: R_GlobalEnv&gt;</code></pre>
<ol style="list-style-type: lower-alpha">
<li>Pour les facteurs <code>Block</code> et <code>Variety</code>, quel type de contrastes devriez-vous utiliser pour comparer l’effet de chaque catégorie à la moyenne, plutôt qu’à une catégorie de référence? Spécifiez ce type de contrastes et nommez les variables de contraste pour en faciliter l’interprétation.</li>
</ol>
<p><strong>Réponse</strong></p>
<pre class="r"><code>contrasts(Oats$Block) &lt;- &quot;contr.sum&quot;
# Ajout de noms aux contrastes (correspondant aux N - 1 premiers niveaux)
colnames(contrasts(Oats$Block)) &lt;- levels(Oats$Block)[-6]

contrasts(Oats$Variety) &lt;- &quot;contr.sum&quot;
colnames(contrasts(Oats$Variety)) &lt;- levels(Oats$Variety)[-3]</code></pre>
<ol start="2" style="list-style-type: lower-alpha">
<li>Estimez les paramètres d’un modèle linéaire du rendement en fonction de la concentration d’azote, de la variété d’avoine et d’un effet <em>fixe</em> du bloc. Vérifiez s’il est utile d’inclure l’interaction entre l’azote et la variété. Que signifierait une telle interaction?</li>
</ol>
<p><strong>Réponse</strong></p>
<p>Une interaction signifierait que l’effet de l’azote sur le rendement varie d’une variété à l’autre.</p>
<p>Pour vérifier si l’interaction est significative entre une variable catégorielle et une variable numérique, nous pouvons consulter le tableau d’ANOVA du modèle avec l’interaction. Celui-ci montre que l’interaction n’est pas significative.</p>
<pre class="r"><code>mod1b_inter &lt;- lm(yield ~ nitro * Variety + Block, Oats)
anova(mod1b_inter)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: yield
##               Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
## nitro          1 19536.4 19536.4 81.5155 7.648e-13 ***
## Variety        2  1786.4   893.2  3.7268   0.02972 *  
## Block          5 15875.3  3175.1 13.2479 9.642e-09 ***
## nitro:Variety  2   168.3    84.2  0.3512   0.70524    
## Residuals     61 14619.6   239.7                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Nous aurions aussi pu comparer l’AICc du modèle avec et sans interaction, qui confirme que le modèle sans interaction est préférable.</p>
<pre class="r"><code>mod1b &lt;- lm(yield ~ nitro + Variety + Block, Oats)

library(AICcmodavg)
aictab(list(sans_inter = mod1b, avec_inter = mod1b_inter))</code></pre>
<pre><code>## 
## Model selection based on AICc:
## 
##             K   AICc Delta_AICc AICcWt Cum.Wt      LL
## sans_inter 10 611.33       0.00   0.92   0.92 -293.86
## avec_inter 12 616.18       4.86   0.08   1.00 -293.45</code></pre>
<ol start="3" style="list-style-type: lower-alpha">
<li>Choisissez le modèle avec ou sans interaction selon votre résultat en (b), vérifiez les graphiques de diagnostic et interprétez la valeur des coefficients.</li>
</ol>
<p><strong>Réponse</strong></p>
<pre class="r"><code>plot(mod1b) # Modèle sans interaction</code></pre>
<p><img src="11R-Modèles_mixtes_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>Il n’y a pas de tendance marquée pour les résidus. Le diagramme quantile-quantile montre que les observations ont un peu <em>moins</em> de valeurs extrêmes qu’une distribution normale (car les quantiles des résidus aux deux extrémités sont plus près de 0 que les quantiles théoriques).</p>
<pre class="r"><code>summary(mod1b)</code></pre>
<pre><code>## 
## Call:
## lm(formula = yield ~ nitro + Variety + Block, data = Oats)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -30.519 -12.959   0.781  10.706  34.631 
## 
## Coefficients:
##                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)         81.8722     3.0213  27.098  &lt; 2e-16 ***
## nitro               73.6667     8.0748   9.123 3.97e-13 ***
## VarietyGolden Rain   0.5278     2.5535   0.207  0.83692    
## VarietyMarvellous    5.8194     2.5535   2.279  0.02606 *  
## BlockVI             -7.7222     4.0374  -1.913  0.06034 .  
## BlockV             -13.0556     4.0374  -3.234  0.00195 ** 
## BlockIII            -8.0556     4.0374  -1.995  0.05035 .  
## BlockIV             -5.8056     4.0374  -1.438  0.15540    
## BlockII              3.2778     4.0374   0.812  0.41993    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 15.32 on 63 degrees of freedom
## Multiple R-squared:  0.7155, Adjusted R-squared:  0.6794 
## F-statistic: 19.81 on 8 and 63 DF,  p-value: 1.507e-14</code></pre>
<ul>
<li>L’ordonnée à l’origine est le rendement moyen à une concentration d’azote de 0.</li>
<li>Le rendement augmente d’environ 74 par unité de concentration d’azote. <em>Note</em>: Puisque la concentration varie entre 0 et 0.6, il serait plus utile de diviser cette valeur, ex.: le rendement augmente de 7.4 par augmentation de 0.1 unités d’azote.</li>
<li>Les variétés <em>Golden Rain</em> et <em>Marvellous</em> ont un rendement supérieur de 0.5 et 5.8 à la moyenne, respectivement. La troisième variété (<em>Victory</em>) a un rendement inférieur de 6.3 à la moyenne (-(0.5 + 5.8)).</li>
<li>De même, les coefficients des blocs donnent la différence de rendement moyen entre ce bloc et la moyenne générale. Le dernier bloc (BlockI) a un rendement supérieur de 31.4 à la moyenne (la somme des six différences doit être 0 pour <code>contr.sum</code>).</li>
</ul>
<ol start="4" style="list-style-type: lower-alpha">
<li>Estimez maintenant les paramètres d’un modèle mixte identique au modèle linéaire en (c), excepté que l’effet des blocs est aléatoire plutôt que fixe. Comparez les effets fixes communs aux deux modèles, ainsi que les effets fixes de bloc du modèle précédent aux effets aléatoires par bloc de ce nouveau modèle. Expliquez les différences que vous observez, s’il y a lieu.</li>
</ol>
<p><strong>Réponse</strong></p>
<p>Les fonctions <code>fixef</code> et <code>ranef</code> permettent d’obtenir les effets fixes et aléatoires du modèle mixte.</p>
<pre class="r"><code>library(lme4)
mod1d &lt;- lmer(yield ~ nitro + Variety + (1 | Block), Oats)

fixef(mod1d)</code></pre>
<pre><code>##        (Intercept)              nitro VarietyGolden Rain 
##         81.8722222         73.6666667          0.5277778 
##  VarietyMarvellous 
##          5.8194444</code></pre>
<pre class="r"><code>ranef(mod1d)</code></pre>
<pre><code>## $Block
##     (Intercept)
## VI    -7.151326
## V    -12.090372
## III   -7.460016
## IV    -5.376357
## II     3.035455
## I     29.042616</code></pre>
<p>Les effets fixes (ordonnée à l’origine, azote et variétés) sont les mêmes pour les deux modèles.</p>
<ul>
<li><em>Note</em>: Ici, on a un plan d’expérience complètement équilibré, avec les mêmes combinaisons de variétés et de concentrations d’azote dans chaque bloc. Si ce n’était pas le cas, on ne s’attendrait pas à ce que les effets estimés pour l’azote et la variété soient les mêmes dans les deux versions du modèle.</li>
</ul>
<p>Les effets aléatoires de bloc sont moins extrêmes que les effets fixes du modèle précédent (ex.: -7.2 au lieu de -7.7 pour le bloc VI, 29.0 plutôt que 31.4 pour le bloc I). Cela est conforme avec l’idée que le modèle mixte contracte les effets aléatoires.</p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Calculez la corrélation intra-classe pour le modèle mixte en (d). Quelle est la signification mathématique de ce coefficient? Comment interprétez-vous de résultat d’un point de vue biologique?</li>
</ol>
<p><strong>Réponse</strong></p>
<p>La corrélation intra-classe est obtenue en divisant la variance des effets aléatoires de groupe (blocs) par la somme de la variance de groupe et la variance résiduelle. Ces valeurs apparaissent dans le résultat sommaire du modèle.</p>
<pre class="r"><code>summary(mod1d)</code></pre>
<pre><code>## Linear mixed model fit by REML [&#39;lmerMod&#39;]
## Formula: yield ~ nitro + Variety + (1 | Block)
##    Data: Oats
## 
## REML criterion at convergence: 590.2
## 
## Scaled residuals: 
##      Min       1Q   Median       3Q      Max 
## -1.84069 -0.80849  0.04022  0.70484  2.22148 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  Block    (Intercept) 245.0    15.65   
##  Residual             234.7    15.32   
## Number of obs: 72, groups:  Block, 6
## 
## Fixed effects:
##                    Estimate Std. Error t value
## (Intercept)         81.8722     7.0687  11.582
## nitro               73.6667     8.0748   9.123
## VarietyGolden Rain   0.5278     2.5535   0.207
## VarietyMarvellous    5.8194     2.5535   2.279
## 
## Correlation of Fixed Effects:
##             (Intr) nitro  VrtyGR
## nitro       -0.343              
## VartyGldnRn  0.000  0.000       
## VartyMrvlls  0.000  0.000 -0.500</code></pre>
<pre class="r"><code>cic &lt;- 245 / (234.7 + 245) 
cic</code></pre>
<pre><code>## [1] 0.5107359</code></pre>
<p>Ce coefficient signifie qu’après avoir tenu compte des effets fixes (variété et azote), la variation entre les blocs compte pour 51% de la variation restante, l’autre 49% étant la variation entre observations d’un même bloc. D’un point de vue biologique, cela signifie que les facteurs aléatoires à grande échelle (bloc) et à petite échelle (quadrant) ont une influence environ égale sur le rendement observé.</p>
</div>
<div id="indicateurs-dune-maladie-chez-les-abeilles" class="section level2">
<h2>2. Indicateurs d’une maladie chez les abeilles</h2>
<p>La loque américaine est une maladie infectieuse affectant les colonies d’abeille. Le tableau de données <a href="bees.csv" class="uri">bees.csv</a>, tiré du manuel de Zuur et al. <em>Mixed Effects Models and Extensions in Ecology with R</em>, contient des mesures de la densité de spores bactériennes (<code>Spobee</code>) relevée sur 72 abeilles provenant de 24 ruches (<code>Hive</code>, 3 abeilles par ruche).</p>
<p>Nous voulons déterminer la relation entre cette densité de spores et deux variables définies par ruche: le niveau d’infection observé dans la ruche (<code>Infection</code>) et un estimé de la taille de la colonie (<code>BeesN</code>).</p>
<pre class="r"><code>bees &lt;- read.csv(&quot;bees.csv&quot;)
str(bees)</code></pre>
<pre><code>## &#39;data.frame&#39;:    72 obs. of  7 variables:
##  $ Rawdata  : num  2 4 2 2 6 0 6 2 5 10 ...
##  $ Spobee   : num  6.67 13.33 6.67 6.67 20 ...
##  $ Hive     : int  1 1 1 2 2 2 3 3 3 4 ...
##  $ X        : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ Y        : num  0 0 0 91 91 91 262 262 262 353 ...
##  $ Infection: int  0 0 0 0 0 0 0 0 0 0 ...
##  $ BeesN    : int  95000 95000 95000 95000 95000 95000 85000 85000 85000 90000 ...</code></pre>
<ol style="list-style-type: lower-alpha">
<li>Avant de modéliser ces données, effectuez les transformations suivantes.</li>
</ol>
<ul>
<li><p>Le niveau d’infection est sur une échelle qualitative (0 = pas de symptômes, 1 = infection légere, 2 = modérée et 3 = sévère). Puisque nous avons très peu de ruches pour les différents niveaux d’infection (1 de niveau 1, 1 de niveau 2 et 2 de niveau 3), créez une nouvelle variable binaire <code>pres_inf</code> qui indique la présence (niveaux 1 à 3) ou l’absence (niveau 0) d’infection.</p></li>
<li><p>La distribution de la réponse <code>Spobee</code> est très asymétrique. Tel que suggéré par Zuur et al., créez une nouvelle variable en appliquant la fonction <code>log1p</code>, équivalente à <em>log(Spobee + 1)</em>. Il s’agit d’une transformation logarithmique où on a préalabement ajouté 1 à la réponse, afin d’éviter de prendre le logarithme de 0.</p></li>
<li><p>Exprimez la taille de la colonie en unités de 10 000 abeilles.</p></li>
</ul>
<p><strong>Réponse</strong></p>
<pre class="r"><code>library(dplyr)

bees &lt;- mutate(bees, logspore = log1p(Spobee),
               pres_inf = Infection &gt; 0, Bees_10k = BeesN / 10000)</code></pre>
<ol start="2" style="list-style-type: lower-alpha">
<li>Estimez les paramètres d’un modèle mixte pour déterminer l’effet de la présence d’infection et de la taille de la colonie sur la densité de spores (transformée) observée sur les abeilles. Quel effet aléatoire serait approprié pour ce problème?</li>
</ol>
<p><strong>Réponse</strong></p>
<p>Puisque les observations sont groupées par ruche, il faut utiliser <code>Hive</code> comme effet aléatoire.</p>
<pre class="r"><code>mod2b &lt;- lmer(logspore ~ pres_inf + Bees_10k + (1 | Hive), bees)
summary(mod2b)</code></pre>
<pre><code>## Linear mixed model fit by REML [&#39;lmerMod&#39;]
## Formula: logspore ~ pres_inf + Bees_10k + (1 | Hive)
##    Data: bees
## 
## REML criterion at convergence: 240.7
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -2.2837 -0.4321  0.1626  0.5108  1.6666 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  Hive     (Intercept) 4.8222   2.1960  
##  Residual             0.6033   0.7767  
## Number of obs: 72, groups:  Hive, 24
## 
## Fixed effects:
##              Estimate Std. Error t value
## (Intercept)    6.8529     1.7920   3.824
## pres_infTRUE   6.1487     1.2704   4.840
## Bees_10k      -0.3953     0.2423  -1.631
## 
## Correlation of Fixed Effects:
##             (Intr) p_TRUE
## pres_nfTRUE -0.358       
## Bees_10k    -0.960  0.257</code></pre>
<ol start="3" style="list-style-type: lower-alpha">
<li>Utilisez des graphiques de diagnostic pour vérifier les suppositions du modèle, incluant la normalité des effets aléatoires.</li>
</ol>
<p><strong>Réponse</strong></p>
<p>Le graphique des résidus vs. valeurs prédites indique un problème possible au niveau de l’homogénéité de la variance: la variance des résidus diminue pour les valeurs prédites plus élevées.</p>
<pre class="r"><code>plot(mod2b)</code></pre>
<p><img src="11R-Modèles_mixtes_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>Le diagramme quantile-quantile des résidus montre une assez bonne normalité (excepté deux valeurs extrêmes en bas).</p>
<pre class="r"><code>qqnorm(residuals(mod2b))
qqline(residuals(mod2b))</code></pre>
<p><img src="11R-Modèles_mixtes_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>Le diagramme quantile-quantile des effets aléatoires semble dévier de la normalité: les points suivent une courbe, indiquant une distribution asymétrique.</p>
<pre class="r"><code>effets_alea &lt;- ranef(mod2b)$Hive$`(Intercept)`
qqnorm(effets_alea)
qqline(effets_alea)</code></pre>
<p><img src="11R-Modèles_mixtes_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>L’asymétrie est plus évidente sur un histogramme des effets aléatoires.</p>
<pre class="r"><code>hist(effets_alea)</code></pre>
<p><img src="11R-Modèles_mixtes_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Quel est le coefficient de corrélation intra-classe de ce modèle? Pour estimer plus précisément les effets fixes de ce modèle, serait-il préférable d’échantillonner plus de ruches, ou plus d’abeilles par ruche?</li>
</ol>
<p><strong>Réponse</strong></p>
<p>D’après les résultats sommaires du modèle en (b), la variance de groupe est de 4.82 et la variance résiduelle est de 0.60, pour une coefficient de 0.89.</p>
<pre class="r"><code>cic &lt;- 4.82 / (4.82 + 0.60)
cic</code></pre>
<pre><code>## [1] 0.8892989</code></pre>
<p>Vu que 89% de la variation aléatoire est présente entre les ruches et seulement 11% entre les individus d’une même ruche, il serait plus utile d’échantilloner davantage de ruches.</p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Quels sont les intervalles de confiance à 95% des effets fixes dans le modèle mixte? Si on remplaçait ce modèle par une régression linéaire ignorant complètement la variable <code>Hive</code>, ces intervalles seraient-ils plus étroits ou plus larges, et pourquoi?</li>
</ol>
<p><strong>Réponse</strong></p>
<p>La fonction <code>confint</code> estime les intervalles de confiance.</p>
<pre class="r"><code>confint(mod2b)</code></pre>
<pre><code>##                   2.5 %      97.5 %
## .sig01        1.5546533  2.82978175
## .sigma        0.6439126  0.96238928
## (Intercept)   3.4315810 10.27421447
## pres_infTRUE  3.7230680  8.57424212
## Bees_10k     -0.8579460  0.06734691</code></pre>
<p>Voici le modèle linéaire sans effet de ruche.</p>
<pre class="r"><code>mod2f &lt;- lm(logspore ~ pres_inf + Bees_10k, bees)
confint(mod2f)</code></pre>
<pre><code>##                   2.5 %    97.5 %
## (Intercept)   4.7924563  8.913339
## pres_infTRUE  4.6878782  7.609432
## Bees_10k     -0.6739221 -0.116677</code></pre>
<p>Ces intervalles de confiance sont moins large que ceux du modèle mixte. En particulier, la variable <code>Bees_10k</code> est significative ici, mais ne l’était pas dans le modèle mixte.</p>
<p>Le modèle linéaire suppose que les 72 observations sont indépendantes et calcule les intervalles de confiance d’après cette supposition. Toutefois, nous avons 3 observations dans chacune des 24 ruches et ces trois observations sont très corrélées, comme le montre le résultat en (e). Dans ce cas, le modèle linéaire surestime la précision des estimés.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
