<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />



<meta name="date" content="2018-11-21" />

<title>Mixed models</title>

<script src="libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="libs/bootstrap-3.3.5/css/spacelab.min.css" rel="stylesheet" />
<script src="libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="libs/navigation-1.1/tabsets.js"></script>
<link href="libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>



<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Mixed models</h1>
<h4 class="date"><em>November 21, 2018</em></h4>

</div>


<div id="effect-of-nitrogen-on-the-yield-of-oat-varieties" class="section level2">
<h2>1. Effect of nitrogen on the yield of oat varieties</h2>
<p>The <code>Oats</code> data frame included in the <em>nlme</em> package shows the results of a split-plot agricultural experiment. The experiment is done in six blocks (<code>Block</code>). Each block is divided into three sections where a different variety of oats is sown (<code>Variety</code>), then each section is divided into four quadrants, each receiving a different concentration of nitrogen (<code>nitro</code>): 0, 0.2, 0.4 or 0.6. The response variable is the oat yield of each of the 72 quadrants (6 blocks x 3 varieties x 4 nitrogen concentrations).</p>
<pre class="r"><code>library(nlme)
data(Oats)
# Changer le bloc en facteur non-ordonné
Oats$Block &lt;- factor(Oats$Block, ordered = FALSE)
str(Oats)</code></pre>
<pre><code>## Classes &#39;nfnGroupedData&#39;, &#39;nfGroupedData&#39;, &#39;groupedData&#39; and &#39;data.frame&#39;:   72 obs. of  4 variables:
##  $ Block  : Factor w/ 6 levels &quot;VI&quot;,&quot;V&quot;,&quot;III&quot;,..: 6 6 6 6 6 6 6 6 6 6 ...
##  $ Variety: Factor w/ 3 levels &quot;Golden Rain&quot;,..: 3 3 3 3 1 1 1 1 2 2 ...
##  $ nitro  : num  0 0.2 0.4 0.6 0 0.2 0.4 0.6 0 0.2 ...
##  $ yield  : num  111 130 157 174 117 114 161 141 105 140 ...
##  - attr(*, &quot;formula&quot;)=Class &#39;formula&#39;  language yield ~ nitro | Block
##   .. ..- attr(*, &quot;.Environment&quot;)=&lt;environment: R_GlobalEnv&gt; 
##  - attr(*, &quot;labels&quot;)=List of 2
##   ..$ y: chr &quot;Yield&quot;
##   ..$ x: chr &quot;Nitrogen concentration&quot;
##  - attr(*, &quot;units&quot;)=List of 2
##   ..$ y: chr &quot;(bushels/acre)&quot;
##   ..$ x: chr &quot;(cwt/acre)&quot;
##  - attr(*, &quot;inner&quot;)=Class &#39;formula&#39;  language ~Variety
##   .. ..- attr(*, &quot;.Environment&quot;)=&lt;environment: R_GlobalEnv&gt;</code></pre>
<ol style="list-style-type: lower-alpha">
<li>For the <code>Block</code> and<code>Variety</code> factors, which kind of contrasts should you use to compare the effect of each category to the mean, rather than to a reference category? Specify this type of contrast and name the contrast variables to facilitate the interpretation.</li>
</ol>
<p><strong>Answer</strong></p>
<pre class="r"><code>contrasts(Oats$Block) &lt;- &quot;contr.sum&quot;
# Adding names to contrasts (matching the first N-1 levels)
colnames(contrasts(Oats$Block)) &lt;- levels(Oats$Block)[-6]

contrasts(Oats$Variety) &lt;- &quot;contr.sum&quot;
colnames(contrasts(Oats$Variety)) &lt;- levels(Oats$Variety)[-3]</code></pre>
<ol start="2" style="list-style-type: lower-alpha">
<li>Estimate the parameters of a linear model of yield as a function of nitrogen concentration, oat variety and a <em>fixed</em> effect of the block. Check if it is useful to include the interaction between nitrogen and variety. What would such an interaction mean?</li>
</ol>
<p><strong>Answer</strong></p>
<p>An interaction would mean that the effect of nitrogen on yield varies from variety to variety.</p>
<p>To check if the interaction is significant between a categorical variable and a numeric variable, we can look at the ANOVA table of the model with the interaction. This shows that the interaction is not significant.</p>
<pre class="r"><code>mod1b_inter &lt;- lm(yield ~ nitro * Variety + Block, Oats)
anova(mod1b_inter)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: yield
##               Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
## nitro          1 19536.4 19536.4 81.5155 7.648e-13 ***
## Variety        2  1786.4   893.2  3.7268   0.02972 *  
## Block          5 15875.3  3175.1 13.2479 9.642e-09 ***
## nitro:Variety  2   168.3    84.2  0.3512   0.70524    
## Residuals     61 14619.6   239.7                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>We could also have compared the AICc for the models with and without interaction, confirming that the no interaction model is preferrable.</p>
<pre class="r"><code>mod1b &lt;- lm(yield ~ nitro + Variety + Block, Oats)

library(AICcmodavg)
aictab(list(sans_inter = mod1b, avec_inter = mod1b_inter))</code></pre>
<pre><code>## 
## Model selection based on AICc:
## 
##             K   AICc Delta_AICc AICcWt Cum.Wt      LL
## sans_inter 10 611.33       0.00   0.92   0.92 -293.86
## avec_inter 12 616.18       4.86   0.08   1.00 -293.45</code></pre>
<ol start="3" style="list-style-type: lower-alpha">
<li>Choose the model with or without interaction according to your result in (b), check the diagnostic graphs and interpret the value of the coefficients.</li>
</ol>
<p><strong>Answer</strong></p>
<pre class="r"><code>plot(mod1b) # Model without interaction</code></pre>
<p><img src="11RE-Mixed_models_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>There is no marked trend for residuals. The quantile-quantile plot shows that the observations have a little <em>less</em> extreme values than a normal distribution (because the quantiles of the residuals at both ends are closer to 0 than the theoretical quantiles).</p>
<pre class="r"><code>summary(mod1b)</code></pre>
<pre><code>## 
## Call:
## lm(formula = yield ~ nitro + Variety + Block, data = Oats)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -30.519 -12.959   0.781  10.706  34.631 
## 
## Coefficients:
##                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)         81.8722     3.0213  27.098  &lt; 2e-16 ***
## nitro               73.6667     8.0748   9.123 3.97e-13 ***
## VarietyGolden Rain   0.5278     2.5535   0.207  0.83692    
## VarietyMarvellous    5.8194     2.5535   2.279  0.02606 *  
## BlockVI             -7.7222     4.0374  -1.913  0.06034 .  
## BlockV             -13.0556     4.0374  -3.234  0.00195 ** 
## BlockIII            -8.0556     4.0374  -1.995  0.05035 .  
## BlockIV             -5.8056     4.0374  -1.438  0.15540    
## BlockII              3.2778     4.0374   0.812  0.41993    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 15.32 on 63 degrees of freedom
## Multiple R-squared:  0.7155, Adjusted R-squared:  0.6794 
## F-statistic: 19.81 on 8 and 63 DF,  p-value: 1.507e-14</code></pre>
<ul>
<li>The intercept is the average yield at a nitrogen concentration of 0.</li>
<li>The yield increases by about 74 per unit increase in nitrogen concentration. <em>Note</em>: Since the concentration varies between 0 and 0.6, it would be more useful to divide this value, e.g. the yield increases by 7.4 for each 0.1 units of nitrogen.</li>
<li><em>Golden Rain</em> and <em>Marvelous</em> varieties are 0.5 and 5.8 above average, respectively. The third variety (<em>Victory</em>) has a yield 6.3 lower than the average (- (0.5 + 5.8)).</li>
<li>Similarly, the coefficients of the blocks give the mean yield difference between that block and the overall mean. The last block (BlockI) has a yield 31.4 higher than the mean (the sum of the six differences must be 0 for <code>contr.sum</code>).</li>
</ul>
<ol start="4" style="list-style-type: lower-alpha">
<li>Now estimate the parameters of a mixed model identical to the linear model in (c), except that the effect of the blocks is random rather than fixed. Compare the fixed effects common to both models, as well as the block fixed effects of the previous model to the random effects of this new model. Explain the differences you observe, if any.</li>
</ol>
<p><strong>Answer</strong></p>
<p>The <code>fixef</code> and <code>ranef</code> functions give us the fixed and random effects of the mixed model.</p>
<pre class="r"><code>library(lme4)
mod1d &lt;- lmer(yield ~ nitro + Variety + (1 | Block), Oats)

fixef(mod1d)</code></pre>
<pre><code>##        (Intercept)              nitro VarietyGolden Rain 
##         81.8722222         73.6666667          0.5277778 
##  VarietyMarvellous 
##          5.8194444</code></pre>
<pre class="r"><code>ranef(mod1d)</code></pre>
<pre><code>## $Block
##     (Intercept)
## VI    -7.151326
## V    -12.090372
## III   -7.460016
## IV    -5.376357
## II     3.035455
## I     29.042616</code></pre>
<p>The fixed effects (intercept, nitrogen, and varieties) are the same for both models.</p>
<ul>
<li><em>Note</em>: Here, we have a completely balanced design, with the same combinations of varieties and nitrogen concentrations in each block. If this were not the case, we would not expect the estimated effects for nitrogen and variety to be the same in both versions of the model.</li>
</ul>
<p>The random block effects are less extreme than the fixed effects of the previous model (e.g. -7.2 instead of -7.7 for block VI, 29.0 rather than 31.4 for block I). This is consistent with the idea that the mixed model shrinks random effects.</p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Calculate the intra-class correlation for the mixed model in (d). What is the mathematical significance of this coefficient? How do you interpret the result from a biological point of view?</li>
</ol>
<p><strong>Answer</strong></p>
<p>The intra-class correlation is obtained by dividing the variance of the group random effects (blocks) by the sum of the group variance and the residual variance. These values appear in the summary result of the model.</p>
<pre class="r"><code>summary(mod1d)</code></pre>
<pre><code>## Linear mixed model fit by REML [&#39;lmerMod&#39;]
## Formula: yield ~ nitro + Variety + (1 | Block)
##    Data: Oats
## 
## REML criterion at convergence: 590.2
## 
## Scaled residuals: 
##      Min       1Q   Median       3Q      Max 
## -1.84069 -0.80849  0.04022  0.70484  2.22148 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  Block    (Intercept) 245.0    15.65   
##  Residual             234.7    15.32   
## Number of obs: 72, groups:  Block, 6
## 
## Fixed effects:
##                    Estimate Std. Error t value
## (Intercept)         81.8722     7.0687  11.582
## nitro               73.6667     8.0748   9.123
## VarietyGolden Rain   0.5278     2.5535   0.207
## VarietyMarvellous    5.8194     2.5535   2.279
## 
## Correlation of Fixed Effects:
##             (Intr) nitro  VrtyGR
## nitro       -0.343              
## VartyGldnRn  0.000  0.000       
## VartyMrvlls  0.000  0.000 -0.500</code></pre>
<pre class="r"><code>cic &lt;- 245 / (234.7 + 245) 
cic</code></pre>
<pre><code>## [1] 0.5107359</code></pre>
<p>This coefficient means that after taking into account the fixed effects (variety and nitrogen), the variation between the blocks accounts for 51% of the remaining variance, the other 49% being the variation between observations of the same block. From a biological point of view, this means that large-scale (block) and small-scale (quadrant) random factors have about equal influence on observed yield.</p>
</div>
<div id="indicators-of-disease-in-bees" class="section level2">
<h2>2. Indicators of disease in bees</h2>
<p>American foulbrood is an infectious disease affecting bee colonies. The <a href="bees.csv" class="uri">bees.csv</a> dataset, from the Zuur et al. textbook <em>Mixed Effects Models and Extensions in Ecology with R</em>, contains measurements of bacterial spore density (<code>Spobee</code>) found on 72 bees from 24 hives (<code>Hive</code>, 3 bees per hive).</p>
<p>We want to determine the relationship between this density of spores and two variables defined for each hive: the level of infection observed in the hive (<code>Infection</code>) and an estimate of the size of the colony (<code>BeesN</code>).</p>
<pre class="r"><code>bees &lt;- read.csv(&quot;bees.csv&quot;)
str(bees)</code></pre>
<pre><code>## &#39;data.frame&#39;:    72 obs. of  7 variables:
##  $ Rawdata  : num  2 4 2 2 6 0 6 2 5 10 ...
##  $ Spobee   : num  6.67 13.33 6.67 6.67 20 ...
##  $ Hive     : int  1 1 1 2 2 2 3 3 3 4 ...
##  $ X        : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ Y        : num  0 0 0 91 91 91 262 262 262 353 ...
##  $ Infection: int  0 0 0 0 0 0 0 0 0 0 ...
##  $ BeesN    : int  95000 95000 95000 95000 95000 95000 85000 85000 85000 90000 ...</code></pre>
<ol style="list-style-type: lower-alpha">
<li>Before modeling these data, perform the following transformations.</li>
</ol>
<ul>
<li><p>The level of infection is on a qualitative scale (0 = no symptoms, 1 = mild infection, 2 = moderate and 3 = severe). Since we have very few hives for the different levels of infection (1 level 1, 1 level 2, and 2 level 3), create a new <code>pres_inf</code> binary variable that indicates presence (levels 1 to 3) or absence (level 0) of infection.</p></li>
<li><p>The distribution of the <code>Spobee</code> response is very asymmetrical. As suggested by Zuur et al., create a new variable by applying the <code>log1p</code> function, equivalent to <em>log(Spobee + 1)</em>. This is a logarithmic transformation where 1 has been added to the response beforehand to avoid taking the logarithm of 0.</p></li>
<li><p>Express the size of the colony in units of 10,000 bees.</p></li>
</ul>
<p><strong>Answer</strong></p>
<pre class="r"><code>library(dplyr)

bees &lt;- mutate(bees, logspore = log1p(Spobee),
               pres_inf = Infection &gt; 0, Bees_10k = BeesN / 10000)</code></pre>
<ol start="2" style="list-style-type: lower-alpha">
<li>Estimate the parameters of a mixed model to determine the effect of presence of infection and colony size on the (transformed) spore density observed on bees. Which random effect would be appropriate for this problem?</li>
</ol>
<p><strong>Answer</strong></p>
<p>Since observations are grouped by hive, we use <code>Hive</code> as the random effect.</p>
<pre class="r"><code>mod2b &lt;- lmer(logspore ~ pres_inf + Bees_10k + (1 | Hive), bees)
summary(mod2b)</code></pre>
<pre><code>## Linear mixed model fit by REML [&#39;lmerMod&#39;]
## Formula: logspore ~ pres_inf + Bees_10k + (1 | Hive)
##    Data: bees
## 
## REML criterion at convergence: 240.7
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -2.2837 -0.4321  0.1626  0.5108  1.6666 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  Hive     (Intercept) 4.8222   2.1960  
##  Residual             0.6033   0.7767  
## Number of obs: 72, groups:  Hive, 24
## 
## Fixed effects:
##              Estimate Std. Error t value
## (Intercept)    6.8529     1.7920   3.824
## pres_infTRUE   6.1487     1.2704   4.840
## Bees_10k      -0.3953     0.2423  -1.631
## 
## Correlation of Fixed Effects:
##             (Intr) p_TRUE
## pres_nfTRUE -0.358       
## Bees_10k    -0.960  0.257</code></pre>
<ol start="3" style="list-style-type: lower-alpha">
<li>Use diagnostic graphs to verify model assumptions, including the normality of random effects.</li>
</ol>
<p><strong>Answer</strong></p>
<p>The graph of residuals vs. fitted values indicates a possible problem with homogeneity of variance: the variance of the residuals decreases for the higher predicted values.</p>
<pre class="r"><code>plot(mod2b)</code></pre>
<p><img src="11RE-Mixed_models_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>The quantile-quantile plot of the residuals shows a fairly good normality (except for two extreme values at the bottom).</p>
<pre class="r"><code>qqnorm(residuals(mod2b))
qqline(residuals(mod2b))</code></pre>
<p><img src="11RE-Mixed_models_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>The quantile-quantile plot of the random effects seems to deviate from normality: the points follow a curve, indicating an asymmetric distribution.</p>
<pre class="r"><code>effets_alea &lt;- ranef(mod2b)$Hive$`(Intercept)`
qqnorm(effets_alea)
qqline(effets_alea)</code></pre>
<p><img src="11RE-Mixed_models_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>The asymmetry is more evident in a histogram of the random effects.</p>
<pre class="r"><code>hist(effets_alea)</code></pre>
<p><img src="11RE-Mixed_models_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>What is the intra-class correlation coefficient of this model? To more accurately estimate the fixed effects of this model, would it be better to sample more hives, or more bees per hive?</li>
</ol>
<p><strong>Answer</strong></p>
<p>According to the summary results of the model in (b), the group variance is 4.82 and the residual variance is 0.60, for a coefficient of 0.89.</p>
<pre class="r"><code>cic &lt;- 4.82 / (4.82 + 0.60)
cic</code></pre>
<pre><code>## [1] 0.8892989</code></pre>
<p>Since 89% of the random variation is present between hives and only 11% between individuals in the same hive, it would be more useful to sample more hives.</p>
<ol start="5" style="list-style-type: lower-alpha">
<li>What are the 95% confidence intervals for fixed effects in the mixed model? If we replace this model with a linear regression completely ignoring the <code>Hive</code> variable, would these intervals be narrower or wider, and why?</li>
</ol>
<p><strong>Answer</strong></p>
<p>The <code>confint</code> function estimates confidence intervals.</p>
<pre class="r"><code>confint(mod2b)</code></pre>
<pre><code>##                   2.5 %      97.5 %
## .sig01        1.5546533  2.82978175
## .sigma        0.6439126  0.96238928
## (Intercept)   3.4315810 10.27421447
## pres_infTRUE  3.7230680  8.57424212
## Bees_10k     -0.8579460  0.06734691</code></pre>
<p>Here is the linear regression without hive effects.</p>
<pre class="r"><code>mod2f &lt;- lm(logspore ~ pres_inf + Bees_10k, bees)
confint(mod2f)</code></pre>
<pre><code>##                   2.5 %    97.5 %
## (Intercept)   4.7924563  8.913339
## pres_infTRUE  4.6878782  7.609432
## Bees_10k     -0.6739221 -0.116677</code></pre>
<p>These confidence intervals are more narrow than those of the mixed model. In particular, the variable <code>Bees_10k</code> is significant here, but was not in the mixed model.</p>
<p>The linear regression assumes that the 72 observations are independent and calculates the confidence intervals according to this assumption. However, we have 3 observations in each of the 24 hives and these three observations are highly correlated, as shown by the result in (e). In this case, the linear model overestimates the precision of the estimates.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
