---
title: "Tableaux de contingence"
date: "26 septembre 2018"
output: pdf_document
---

Ce laboratoire doit être remis le **3 octobre à 17h sur Moodle**. Dans votre réponse pour chaque question, veuillez inclure une copie du code R utilisé (s'il y a lieu) et des résultats obtenus. 


## 1. Sélection florale d'une espèce de bourdon

En suivant l'activité de butinage de bourdons fébriles (*Bombus impatiens*) sur un site, vous notez le nombre de visites des bourdons sur quatre genres de plantes, ainsi que la proportion des fleurs de chaque genre sur le site.

| Genre | Nombre de visites | Proportions des fleurs du site |
|---------+---+------|
| *Rubus* | 6 | 0.12 |
| *Solidago* | 8 | 0.24 |
| *Trifolium* | 20 | 0.33 |
| *Vaccinium* | 11 | 0.31 |

L'hypothèse nulle pour cette étude est que *B. impatiens* visite chaque genre proportionnellement à sa prévalence sur le site.

a) Selon l'hypothèse nulle, quelles sont les fréquences attendues pour les visites à chaque genre de plante?

b) Testez l'hypothèse nulle avec la fonction `chisq.test` dans R, avec un seuil de signification de 5%. Si l'hypothèse nulle est rejetée, quel(s) genre(s) sont plus ou moins visités que prévus?


## 2. Butinage de trois espèces de bourdon

Sur le même site que l'exercice précédent, vous observez l'activité de butinage de deux autres espèces de bourdons (*B. affinis* et *B. ternarius*). Voici le tableau de contingence montrant le nombre de visites par espèce de bourdon et par genre de plante.

| | *Rubus* | *Solidago* | *Trifolium* | *Vaccinium* |
|-+---------+------------+-------------+-------------|
| *B. affinis* | 10 | 9 | 15 | 8 |
| *B. impatiens* | 6 | 8 | 20 | 11 |
| *B. ternarius* | 18 | 4 | 11 | 5 |

a) Quelle hypothèse nulle pouvez-vous tester à partir de ce tableau? Quelle est l'hypothèse alternative?

b) Créez une matrice représentant ce tableau dans R, puis testez l'hypothèse nulle mentionnée en (a) avec la fonction `chisq.test`, avec un seuil de signification de 5%.

c) D'après les résultats du test en (b), quel est le nombre de degrés de liberté du $\chi^2$? Comment cette valeur est-elle calculée?

d) Comment pouvez-vous consulter les fréquences attendues selon l'hypothèse nulle, ainsi que les résidus?

e) Si l'hypothèse nulle est rejetée, quelle paire bourdon-plante a le résidu le plus positif, et laquelle a le résidu le plus négatif? Comment interprétez-vous ces résidus?


## 3. Applications du $\chi^2$

Voici trois questions de foresterie urbaine. Pour laquelle de ces questions le test du $\chi^2$ est-il le plus approprié? Justifiez votre réponse.

a) Est-ce que l'âge moyen des arbres dans différents quartiers d'une ville augmente avec l'âge moyen des maisons du quartier?

b) La présence d'un grand arbre affecte-t-elle le coût en énergie d'une maison?

c) Est-ce que la distribution des espèces d'arbres plantés diffère entre les quartiers?



