<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>Régression linéaire</title>

<script src="libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="libs/bootstrap-3.3.5/css/spacelab.min.css" rel="stylesheet" />
<script src="libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="libs/navigation-1.1/tabsets.js"></script>
<link href="libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>



<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Régression linéaire</h1>
<h4 class="date"><em>17 octobre 2018</em></h4>

</div>


<div id="metabolisme-dun-poisson-selon-la-salinite" class="section level2">
<h2>1. Métabolisme d’un poisson selon la salinité</h2>
<p>Le tableau de données <a href="sardinella.csv" class="uri">sardinella.csv</a> provient d’une étude de Wohlschlag (1957), “Differences in metabolic rates of migratory and resident freshwater forms of an Arctic Whitefish”. Il contient des mesures du poids (<em>log_weight</em>) et de la consommation en oxygène (<em>log_O2</em>) pour des individus du corgéone <em>Coregonus sardinella</em> capturés dans un environnement d’eau douce (<em>freshwater</em>) ou d’eau salée (<em>marine</em>).</p>
<pre class="r"><code>sardinella &lt;- read.csv(&quot;sardinella.csv&quot;)
str(sardinella)</code></pre>
<pre><code>## &#39;data.frame&#39;:    22 obs. of  3 variables:
##  $ environment: Factor w/ 2 levels &quot;freshwater&quot;,&quot;marine&quot;: 2 2 2 2 2 2 2 2 1 1 ...
##  $ log_O2     : num  1.59 1.4 1.47 1.66 1.55 ...
##  $ log_weight : num  2.5 2.04 2.15 2.35 2.24 ...</code></pre>
<ol style="list-style-type: lower-alpha">
<li>Estimez les effets additifs de l’environnement et du poids sur la consommation en oxygène de ce poisson. Comment interprétez-vous chacun des paramètres du modèle?</li>
</ol>
<p><strong>Réponse</strong></p>
<pre class="r"><code>mod1a &lt;- lm(log_O2 ~ environment + log_weight, data = sardinella)
summary(mod1a)</code></pre>
<pre><code>## 
## Call:
## lm(formula = log_O2 ~ environment + log_weight, data = sardinella)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.28074 -0.02670  0.01742  0.05373  0.16339 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       -0.06836    0.31719  -0.216 0.831654    
## environmentmarine  0.15544    0.04402   3.531 0.002233 ** 
## log_weight         0.65310    0.13815   4.728 0.000146 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.0968 on 19 degrees of freedom
## Multiple R-squared:  0.6023, Adjusted R-squared:  0.5605 
## F-statistic: 14.39 on 2 and 19 DF,  p-value: 0.0001568</code></pre>
<ul>
<li><code>Intercept</code> correspond à l’ordonnée à l’origine (valeur de <em>log_O2</em> si <em>log_weight</em> = 0) en eau douce.</li>
<li><code>environmentmarine</code> est la différence entre <em>log_O2</em> en eau salée et en eau douce. Les poissons en eau salée consomment plus d’oxygène pour un même poids.</li>
<li><code>log_weight</code> est l’augmentation de <em>log_O2</em> lorsque <em>log_weight</em> augmente de 1.</li>
</ul>
<p><strong>Rappel sur l’interprétation des logarithmes</strong>: Un logarithme de 0 correspond à une valeur de 1 et un logarithme négatif correspond une valeur &lt; 1 de la variable originale. Une addition de 1 sur l’échelle logarithmique correspond à une multiplication par <em>e</em> (environ 2.7) de la variable originale.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Reprenez le modèle en (a) avec une version normalisée du prédicteur <em>log_weight</em> (<em>norm_weight</em>). Quelle est maintenant l’interprétation des coefficients?</li>
</ol>
<p><strong>Réponse</strong></p>
<pre class="r"><code>sardinella$norm_weight &lt;- scale(sardinella$log_weight)
mod1b &lt;- lm(log_O2 ~ environment + norm_weight, data = sardinella)
summary(mod1b)</code></pre>
<pre><code>## 
## Call:
## lm(formula = log_O2 ~ environment + norm_weight, data = sardinella)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.28074 -0.02670  0.01742  0.05373  0.16339 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)        1.40925    0.02612  53.955  &lt; 2e-16 ***
## environmentmarine  0.15544    0.04402   3.531 0.002233 ** 
## norm_weight        0.10247    0.02168   4.728 0.000146 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.0968 on 19 degrees of freedom
## Multiple R-squared:  0.6023, Adjusted R-squared:  0.5605 
## F-statistic: 14.39 on 2 and 19 DF,  p-value: 0.0001568</code></pre>
<ul>
<li><code>Intercept</code> est la valeur de <em>log_O2</em> correspondant à <em>norm_weight</em> = 0, donc à la moyenne de <em>log_weight</em>, en eau douce.</li>
<li><code>environmentmarine</code> est la différence entre <em>log_O2</em> en eau salée et en eau douce (aucun changement).</li>
<li><code>norm_weight</code> est l’augmentation de <em>log_O2</em> lorsque <em>norm_weight</em> augmente de 1, donc lorsque <em>log_weight</em> augmente d’un écart-type.</li>
</ul>
<ol start="3" style="list-style-type: lower-alpha">
<li>Reprenez le modèle en (b) en ajoutant l’interaction entre le poids (normalisé) et l’environnement. Cette interaction est-elle significative? Quelle est l’interprétation des coefficients?</li>
</ol>
<p><strong>Réponse</strong></p>
<pre class="r"><code>mod1c &lt;- lm(log_O2 ~ environment * norm_weight, data = sardinella)
summary(mod1c)</code></pre>
<pre><code>## 
## Call:
## lm(formula = log_O2 ~ environment * norm_weight, data = sardinella)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.25609 -0.04721  0.01152  0.04264  0.16735 
## 
## Coefficients:
##                               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                    1.40521    0.02545  55.207  &lt; 2e-16 ***
## environmentmarine              0.14778    0.04296   3.440 0.002923 ** 
## norm_weight                    0.12689    0.02661   4.769 0.000153 ***
## environmentmarine:norm_weight -0.06479    0.04334  -1.495 0.152265    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.0938 on 18 degrees of freedom
## Multiple R-squared:  0.6463, Adjusted R-squared:  0.5873 
## F-statistic: 10.96 on 3 and 18 DF,  p-value: 0.0002522</code></pre>
<ul>
<li><code>Intercept</code> est la valeur de <em>log_O2</em> correspondant à <em>norm_weight</em> = 0, donc à la moyenne de <em>log_weight</em>, en eau douce (même interprétation qu’avant, mais l’estimé a un peu changé).</li>
<li><code>environmentmarine</code> est la différence entre <em>log_O2</em> en eau salée et en eau douce, pour un poisson avec <em>norm_weight</em> = 0 (donc à la moyenne de <em>log_weight</em>).</li>
<li><code>norm_weight</code> est l’augmentation de <em>log_O2</em> lorsque <em>norm_weight</em> augmente de 1 (la pente de <em>log_O2</em> vs. <em>norm_weight</em>) en eau douce.</li>
<li><code>environmentmarine:norm_weight</code> est la différence de la pente de <em>log_O2</em> vs. <em>norm_weight</em> en eau salée par rapport à sa valeur en eau douce. Puisque l’interaction est négative, l’effet du poids sur la consommation d’oxygène est plus faible en eau salée.</li>
</ul>
<p>Cependant, l’interaction n’est pas significative.</p>
</div>
<div id="diversite-des-plantes-sur-des-iles-britanniques" class="section level2">
<h2>2. Diversité des plantes sur des îles britanniques</h2>
<p>Le tableau de données <a href="britain_species.csv" class="uri">britain_species.csv</a> provient de l’étude de Johnson et Simberloff (1974), “Environmental determinants of island species numbers in the British Isles”. Ces données indiquent le nombre d’espèces de plantes vasculaires (<em>species</em>) pour 42 îles britanniques en fonction de différents prédicteurs: surface en km<span class="math inline">\(^2\)</span> (<em>area</em>), altitude en m (<em>elevation</em>), nombre de types de sol (<em>soil_types</em>), latitude et distance de la Grande-Bretagne en km (<em>dist_britain</em>).</p>
<pre class="r"><code>iles &lt;- read.csv(&quot;britain_species.csv&quot;)
str(iles)</code></pre>
<pre><code>## &#39;data.frame&#39;:    42 obs. of  7 variables:
##  $ island      : Factor w/ 42 levels &quot;Ailsa&quot;,&quot;Anglesey&quot;,..: 1 2 3 4 5 6 7 8 9 10 ...
##  $ area        : num  0.8 712.5 429.4 18.4 31.1 ...
##  $ elevation   : int  340 127 874 384 226 1343 210 103 143 393 ...
##  $ soil_types  : int  1 3 4 2 1 16 1 3 1 1 ...
##  $ latitude    : num  55.3 53.3 55.6 57 60.1 54.3 57.1 56.6 56.1 56.9 ...
##  $ dist_britain: num  14 0.2 5.2 77.4 201.6 ...
##  $ species     : int  75 855 577 409 177 1666 300 443 482 453 ...</code></pre>
<ol style="list-style-type: lower-alpha">
<li>Supposons qu’une théorie prédit que le nombre d’espèces (<span class="math inline">\(S\)</span>) dépend de la surface d’une île (<span class="math inline">\(A\)</span>) en fonction de l’équation suivante, où <span class="math inline">\(c\)</span> et <span class="math inline">\(z\)</span> sont des paramètres à déterminer:</li>
</ol>
<p><span class="math display">\[ S = c A^z \]</span></p>
<p>Utilisez un modèle linéaire pour tester l’hypothèse que le nombre d’espèces de plantes vasculaires suit cette équation avec une exposant <span class="math inline">\(z = 0.25\)</span> (un quart).</p>
<p><em>Indice</em>: Supposons que la valeur estimée de <span class="math inline">\(z\)</span> suit une distribution normale. À partir de la valeur estimée de <span class="math inline">\(z\)</span> et de son erreur-type, utilisez la formule vue au deuxième cours pour calculer l’intervalle de confiance.</p>
<p><span class="math display">\[ (\hat{z} + t_{df, \alpha/2} SE, \hat{z} + t_{df, 1-\alpha/2} SE) \]</span></p>
<p>Dans cette formule, <span class="math inline">\(SE\)</span> est l’erreur-type, <span class="math inline">\(\alpha\)</span> est le seuil de significativité que vous choisissez (ex.: 0.05) et <span class="math inline">\(df\)</span> est le nombre de degrés de liberté de la distribution <span class="math inline">\(t\)</span>, que vous pouvez déterminer à partir du sommaire de la régression.</p>
<p><strong>Réponse</strong></p>
<p>En faisant une transformation logarithmique:</p>
<p><span class="math display">\[ \log(S) = \log(c) + z \log(A) \]</span></p>
<pre class="r"><code>mod2a &lt;- lm(log(species) ~ log(area), data = iles)</code></pre>
<p>Vérifions d’abord les graphiques de diagnostic pour voir si le modèle est approprié.</p>
<p><img src="7R-Régression_linéaire_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>Il n’y a pas de problème, sauf peut-être la tendance sur le graphique <code>Scale-Location</code>. Celle-ci est due à un seul point à droite: il s’agit de l’île de Grande-Bretagne (<code>Britain</code>), qui a une surface beaucoup plus grande que les autres. Donc il ne semble pas que la variance change systématiquement le long de l’axe.</p>
<p>Regardons maintenant les coefficients.</p>
<pre class="r"><code>summary(mod2a)</code></pre>
<pre><code>## 
## Call:
## lm(formula = log(species) ~ log(area), data = iles)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.49954 -0.35374  0.01252  0.35354  0.83936 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  4.83570    0.16930  28.563  &lt; 2e-16 ***
## log(area)    0.20880    0.03447   6.057 3.93e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.5251 on 40 degrees of freedom
## Multiple R-squared:  0.4784, Adjusted R-squared:  0.4653 
## F-statistic: 36.69 on 1 and 40 DF,  p-value: 3.932e-07</code></pre>
<p>L’estimé de <span class="math inline">\(z\)</span> est le coefficient de <code>log(area)</code>, soit 0.2088 avec une erreur-type de 0.03447. Il y a 40 degrés de liberté résiduels. Nous calculons l’intervalle de confiance à 95% à partir des quantiles de la distribution <span class="math inline">\(t\)</span> données par <code>qt</code>.</p>
<pre class="r"><code>z &lt;- 0.2088
se &lt;- 0.03447
conf_int &lt;- c(z + qt(0.025, df = 40) * se, 
              z + qt(0.975, df = 40) * se)
conf_int</code></pre>
<pre><code>## [1] 0.1391335 0.2784665</code></pre>
<p>Puisque la valeur <span class="math inline">\(z = 0.25\)</span> est dans l’intervalle de confiance, nous ne rejetons pas cette hypothèse.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Estimez maintenant le modèle suivant, où le nombre d’espèce dépend à la fois de la surface de l’île et de sa distance de la Grande-Bretagne, sur une échelle logarithmique. Vous devrez d’abord exclure l’île de Grande-Bretagne (<code>Britain</code>) du jeu de données.</li>
</ol>
<p><span class="math display">\[ \log(species) \sim \log(area) + \log(dist\_britain) \]</span></p>
<p><strong>Réponse</strong></p>
<pre class="r"><code>library(dplyr)
iles2 &lt;- filter(iles, island != &quot;Britain&quot;)
mod2b &lt;- lm(log(species) ~ log(area) + log(dist_britain), data = iles2)
summary(mod2b)</code></pre>
<pre><code>## 
## Call:
## lm(formula = log(species) ~ log(area) + log(dist_britain), data = iles2)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.36615 -0.17134  0.02895  0.28216  0.69688 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)        5.41797    0.25435  21.302  &lt; 2e-16 ***
## log(area)          0.18119    0.03842   4.716 3.21e-05 ***
## log(dist_britain) -0.14459    0.04676  -3.092  0.00371 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.4815 on 38 degrees of freedom
## Multiple R-squared:  0.517,  Adjusted R-squared:  0.4916 
## F-statistic: 20.34 on 2 and 38 DF,  p-value: 9.873e-07</code></pre>
<ol start="3" style="list-style-type: lower-alpha">
<li>À partir du modèle en (b), donnez un intervalle de prédiction à 90% du nombre d’espèces pour (i) une île de 1 km<span class="math inline">\(^2\)</span> située à une distance de 5 km et (ii) une île de 40 km<span class="math inline">\(^2\)</span> située à une distance de 20 km.</li>
</ol>
<p><em>Notes</em>:</p>
<ul>
<li><p>Modifiez le % de l’intervalle de prédiction avec l’argument <code>level</code> de <code>predict</code>.</p></li>
<li><p>Puisque la réponse du modèle est <code>log(species)</code>, le résultat de <code>predict</code> sera sur une échelle logarithmique.</p></li>
</ul>
<p><strong>Réponse</strong></p>
<pre class="r"><code># Nouveau tableau pour les prédictions
iles_nouv &lt;- data.frame(area = c(1, 40), dist_britain = c(5, 20))

iles_pred &lt;- predict(mod2b, iles_nouv, interval = &quot;prediction&quot;,
                     level = 0.90)

iles_nouv &lt;- cbind(iles_nouv, iles_pred)
iles_nouv</code></pre>
<pre><code>##   area dist_britain      fit      lwr      upr
## 1    1            5 5.185262 4.302868 6.067657
## 2   40           20 5.653201 4.830675 6.475727</code></pre>
<p>Finalement, transformons les valeurs <code>lwr</code>et <code>upr</code> en nombre d’espèces avec la fonction exponentielle.</p>
<pre class="r"><code>iles_nouv &lt;- mutate(iles_nouv, esp_min = exp(lwr), esp_max = exp(upr))
iles_nouv</code></pre>
<pre><code>##   area dist_britain      fit      lwr      upr   esp_min  esp_max
## 1    1            5 5.185262 4.302868 6.067657  73.91148 431.6680
## 2   40           20 5.653201 4.830675 6.475727 125.29549 649.1908</code></pre>
<p>Nos intervalles de prédiction sont donc de 74 à 432 espèces pour la première île et de 125 à 649 espèces pour la deuxième.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
