<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />



<meta name="date" content="2018-10-17" />

<title>Linear regression</title>

<script src="libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="libs/bootstrap-3.3.5/css/spacelab.min.css" rel="stylesheet" />
<script src="libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="libs/navigation-1.1/tabsets.js"></script>
<link href="libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>



<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Linear regression</h1>
<h4 class="date"><em>October 17, 2018</em></h4>

</div>


<div id="metabolism-of-a-fish-according-to-salinity" class="section level2">
<h2>1. Metabolism of a fish according to salinity</h2>
<p>The dataset <a href="sardinella.csv" class="uri">sardinella.csv</a> comes from a study by Wohlschlag (1957), “Differences in metabolic rates of migratory and resident freshwater forms of an Arctic Whitefish”. It contains weight (<em>log_weight</em>) and oxygen consumption (<em>log_O2</em>) measurements for individuals of <em>Coregonus sardinella</em> caught in freshwater or marine environments.</p>
<pre class="r"><code>sardinella &lt;- read.csv(&quot;sardinella.csv&quot;)
str(sardinella)</code></pre>
<pre><code>## &#39;data.frame&#39;:    22 obs. of  3 variables:
##  $ environment: Factor w/ 2 levels &quot;freshwater&quot;,&quot;marine&quot;: 2 2 2 2 2 2 2 2 1 1 ...
##  $ log_O2     : num  1.59 1.4 1.47 1.66 1.55 ...
##  $ log_weight : num  2.5 2.04 2.15 2.35 2.24 ...</code></pre>
<ol style="list-style-type: lower-alpha">
<li>Estimate the additive effects of environment and weight on the oxygen consumption of this fish. How do you interpret each of the parameters of the model?</li>
</ol>
<p><strong>Answer</strong></p>
<pre class="r"><code>mod1a &lt;- lm(log_O2 ~ environment + log_weight, data = sardinella)
summary(mod1a)</code></pre>
<pre><code>## 
## Call:
## lm(formula = log_O2 ~ environment + log_weight, data = sardinella)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.28074 -0.02670  0.01742  0.05373  0.16339 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       -0.06836    0.31719  -0.216 0.831654    
## environmentmarine  0.15544    0.04402   3.531 0.002233 ** 
## log_weight         0.65310    0.13815   4.728 0.000146 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.0968 on 19 degrees of freedom
## Multiple R-squared:  0.6023, Adjusted R-squared:  0.5605 
## F-statistic: 14.39 on 2 and 19 DF,  p-value: 0.0001568</code></pre>
<ul>
<li><code>Intercept</code> is the intercept (value of <em>log_O2</em> if <em>log_weight</em> = 0) in freshwater.</li>
<li><code>environmentmarine</code> is the difference between <em>log_O2</em> in marine vs. freshwater. Saltwater fish consume more oxygen for the same weight.</li>
<li><code>log_weight</code> is the increase in <em>log_O2</em> when <em>log_weight</em> goes up by 1.</li>
</ul>
<p><strong>Reminder on the interpretation of logarithms</strong>: A logarithm of 0 corresponds to a value of 1 and a negative logarithm corresponds to a value &lt; 1 for the original variable. An increase of 1 on the logarithmic scale corresponds to a multiplication by <em>e</em> (about 2.7) of the original variable.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Repeat the model in (a) with a standardized version of the predictor <em>log_weight</em> (<em>norm_weight</em>). What is the interpretation of the coefficients now?</li>
</ol>
<p><strong>Answer</strong></p>
<pre class="r"><code>sardinella$norm_weight &lt;- scale(sardinella$log_weight)
mod1b &lt;- lm(log_O2 ~ environment + norm_weight, data = sardinella)
summary(mod1b)</code></pre>
<pre><code>## 
## Call:
## lm(formula = log_O2 ~ environment + norm_weight, data = sardinella)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.28074 -0.02670  0.01742  0.05373  0.16339 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)        1.40925    0.02612  53.955  &lt; 2e-16 ***
## environmentmarine  0.15544    0.04402   3.531 0.002233 ** 
## norm_weight        0.10247    0.02168   4.728 0.000146 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.0968 on 19 degrees of freedom
## Multiple R-squared:  0.6023, Adjusted R-squared:  0.5605 
## F-statistic: 14.39 on 2 and 19 DF,  p-value: 0.0001568</code></pre>
<ul>
<li><code>Intercept</code> is the value of <em>log_O2</em> for <em>norm_weight</em> = 0, i.e. the mean value of <em>log_weight</em>, in freshwater.</li>
<li><code>environmentmarine</code> is the difference in <em>log_O2</em> between marine and freshwater (same as before).</li>
<li><code>norm_weight</code> is the increase in <em>log_O2</em> when <em>norm_weight</em> increases by 1, i.e. when <em>log_weight</em> increases by 1 standard deviation.</li>
</ul>
<ol start="3" style="list-style-type: lower-alpha">
<li>Repeat the model in (b) by adding the interaction between the weight (normalized) and the environment. Is this interaction meaningful? What is the interpretation of the coefficients?</li>
</ol>
<p><strong>Answer</strong></p>
<pre class="r"><code>mod1c &lt;- lm(log_O2 ~ environment * norm_weight, data = sardinella)
summary(mod1c)</code></pre>
<pre><code>## 
## Call:
## lm(formula = log_O2 ~ environment * norm_weight, data = sardinella)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.25609 -0.04721  0.01152  0.04264  0.16735 
## 
## Coefficients:
##                               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                    1.40521    0.02545  55.207  &lt; 2e-16 ***
## environmentmarine              0.14778    0.04296   3.440 0.002923 ** 
## norm_weight                    0.12689    0.02661   4.769 0.000153 ***
## environmentmarine:norm_weight -0.06479    0.04334  -1.495 0.152265    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.0938 on 18 degrees of freedom
## Multiple R-squared:  0.6463, Adjusted R-squared:  0.5873 
## F-statistic: 10.96 on 3 and 18 DF,  p-value: 0.0002522</code></pre>
<ul>
<li><code>Intercept</code> is the value of <em>log_O2</em> for <em>norm_weight</em> = 0, i.e. the mean value of <em>log_weight</em>, in freshwater (same interpretation as before, although the estimate varies slightly).</li>
<li><code>environmentmarine</code> is the difference in <em>log_O2</em> between marine and freshwater, for a fish with <em>norm_weight</em> = 0 (at the mean of <em>log_weight</em>).</li>
<li><code>norm_weight</code> is the increase in <em>log_O2</em> when <em>norm_weight</em> goes up by 1 (i.e. the slope of <em>log_O2</em> vs. <em>norm_weight</em>) in freshwater.</li>
<li><code>environmentmarine:norm_weight</code> is the difference between the slope of <em>log_O2</em> vs. <em>norm_weight</em> for marine fish compared to the slope for freshwater fish. Since the interaction is negative, the effect of weight on oxygen consumption is weaker for marine fish.</li>
</ul>
<p>However, the interaction is not significant.</p>
</div>
<div id="diversity-of-plants-on-british-isles" class="section level2">
<h2>2. Diversity of plants on British Isles</h2>
<p>The dataset <a href="britain_species.csv" class="uri">britain_species.csv</a> comes from the study of Johnson and Simberloff (1974), “Environmental determinants of island species numbers in the British Isles”. These data indicate the number of vascular plant species (<em>species</em>) for 42 British isles according to different predictors: area in km<span class="math inline">\(^2\)</span>, elevation in m, number of soil types, latitude and distance from Great Britain in km (<em>dist_britain</em>).</p>
<pre class="r"><code>iles &lt;- read.csv(&quot;britain_species.csv&quot;)
str(iles)</code></pre>
<pre><code>## &#39;data.frame&#39;:    42 obs. of  7 variables:
##  $ island      : Factor w/ 42 levels &quot;Ailsa&quot;,&quot;Anglesey&quot;,..: 1 2 3 4 5 6 7 8 9 10 ...
##  $ area        : num  0.8 712.5 429.4 18.4 31.1 ...
##  $ elevation   : int  340 127 874 384 226 1343 210 103 143 393 ...
##  $ soil_types  : int  1 3 4 2 1 16 1 3 1 1 ...
##  $ latitude    : num  55.3 53.3 55.6 57 60.1 54.3 57.1 56.6 56.1 56.9 ...
##  $ dist_britain: num  14 0.2 5.2 77.4 201.6 ...
##  $ species     : int  75 855 577 409 177 1666 300 443 482 453 ...</code></pre>
<ol style="list-style-type: lower-alpha">
<li>Suppose that a theory predicts that the number of species (<span class="math inline">\(S\)</span>) depends on the area of an island (<span class="math inline">\(A\)</span>) according to the following equation, where <span class="math inline">\(c\)</span> and <span class="math inline">\(z\)</span> are parameters to be determined:</li>
</ol>
<p><span class="math display">\[ S = c A^z \]</span></p>
<p>Use a linear model to test the hypothesis that the number of vascular plant species follows that equation with an exponent <span class="math inline">\(z = 0.25\)</span> (one quarter).</p>
<p><em>Hint</em>: Assume that the estimated value of <span class="math inline">\(z\)</span> follows a normal distribution. From the estimated value of <span class="math inline">\(z\)</span> and its standard error, use the formula seen during the second class to calculate the confidence interval.</p>
<p><span class="math display">\[ (\hat{z} + t_{df, \alpha/2} SE, \hat{z} + t_{df, 1-\alpha/2} SE) \]</span></p>
<p>In this formula, <span class="math inline">\(SE\)</span> is the standard error, <span class="math inline">\(\alpha\)</span> is the significance threshold you choose (ex: 0.05) and <span class="math inline">\(df\)</span> is the number of degrees of freedom of the <span class="math inline">\(t\)</span> distribution, that you can determine from the summary of the regression.</p>
<p><strong>Answer</strong></p>
<p>With a logarithmic transform:</p>
<p><span class="math display">\[ \log(S) = \log(c) + z \log(A) \]</span></p>
<pre class="r"><code>mod2a &lt;- lm(log(species) ~ log(area), data = iles)</code></pre>
<p>Let’s first look at diagnostic plots to see if the model fits.</p>
<p><img src="7RE-Linear_regression_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>There is no problem, except perhaps the trend on the <code>Scale-Location</code> plot. It is due to a single point on the right: it is the island of Britain (<code>Britain</code>), which has a surface much larger than the others. So it does not seem that the variance systematically changes along the axis.</p>
<p>Now let’s look at the coefficients.</p>
<pre class="r"><code>summary(mod2a)</code></pre>
<pre><code>## 
## Call:
## lm(formula = log(species) ~ log(area), data = iles)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.49954 -0.35374  0.01252  0.35354  0.83936 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  4.83570    0.16930  28.563  &lt; 2e-16 ***
## log(area)    0.20880    0.03447   6.057 3.93e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.5251 on 40 degrees of freedom
## Multiple R-squared:  0.4784, Adjusted R-squared:  0.4653 
## F-statistic: 36.69 on 1 and 40 DF,  p-value: 3.932e-07</code></pre>
<p>The estimate of <span class="math inline">\(z\)</span> is the coefficient of <code>log(area)</code>, ie 0.2088 with a standard error of 0.03447. There are 40 residual degrees of freedom. We calculate the 95% confidence interval from the quantiles of the <span class="math inline">\(t\)</span> distribution, given by <code>qt</code>.</p>
<pre class="r"><code>z &lt;- 0.2088
se &lt;- 0.03447
conf_int &lt;- c(z + qt(0.025, df = 40) * se, 
              z + qt(0.975, df = 40) * se)
conf_int</code></pre>
<pre><code>## [1] 0.1391335 0.2784665</code></pre>
<p>Since the value <span class="math inline">\(z = 0.25\)</span> is in the confidence interval, we do not reject this hypothesis.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Now estimate the following model, where the number of species depends both on the area of the island and its distance from Great Britain, on a logarithmic scale. You will first have to exclude the island of Britain from the dataset.</li>
</ol>
<p><span class="math display">\[ \log(species) \sim \log(area) + \log(dist\_britain) \]</span></p>
<p><strong>Answer</strong></p>
<pre class="r"><code>library(dplyr)
iles2 &lt;- filter(iles, island != &quot;Britain&quot;)
mod2b &lt;- lm(log(species) ~ log(area) + log(dist_britain), data = iles2)
summary(mod2b)</code></pre>
<pre><code>## 
## Call:
## lm(formula = log(species) ~ log(area) + log(dist_britain), data = iles2)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.36615 -0.17134  0.02895  0.28216  0.69688 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)        5.41797    0.25435  21.302  &lt; 2e-16 ***
## log(area)          0.18119    0.03842   4.716 3.21e-05 ***
## log(dist_britain) -0.14459    0.04676  -3.092  0.00371 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.4815 on 38 degrees of freedom
## Multiple R-squared:  0.517,  Adjusted R-squared:  0.4916 
## F-statistic: 20.34 on 2 and 38 DF,  p-value: 9.873e-07</code></pre>
<ol start="3" style="list-style-type: lower-alpha">
<li>Using the model in (b), give a 90% prediction interval for the number of species for (i) a 1-km<span class="math inline">\(^2\)</span> island at a distance of 5 km and (ii) an 40-km<span class="math inline">\(^2\)</span> island located at a distance of 20 km.</li>
</ol>
<p><em>Note</em>:</p>
<ul>
<li><p>Change the % of the prediction interval with the <code>level</code> argument of <code>predict</code>.</p></li>
<li><p>Since the response of the model is <code>log(species)</code>, the result of <code>predict</code> will be on a logarithmic scale.</p></li>
</ul>
<p><strong>Answer</strong></p>
<pre class="r"><code># Nouveau tableau pour les prédictions
iles_nouv &lt;- data.frame(area = c(1, 40), dist_britain = c(5, 20))

iles_pred &lt;- predict(mod2b, iles_nouv, interval = &quot;prediction&quot;,
                     level = 0.90)

iles_nouv &lt;- cbind(iles_nouv, iles_pred)
iles_nouv</code></pre>
<pre><code>##   area dist_britain      fit      lwr      upr
## 1    1            5 5.185262 4.302868 6.067657
## 2   40           20 5.653201 4.830675 6.475727</code></pre>
<p>Finally, we transform <code>lwr</code> and <code>upr</code> to numbers of species with the exponential function.</p>
<pre class="r"><code>iles_nouv &lt;- mutate(iles_nouv, esp_min = exp(lwr), esp_max = exp(upr))
iles_nouv</code></pre>
<pre><code>##   area dist_britain      fit      lwr      upr   esp_min  esp_max
## 1    1            5 5.185262 4.302868 6.067657  73.91148 431.6680
## 2   40           20 5.653201 4.830675 6.475727 125.29549 649.1908</code></pre>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
