<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Régression de Poisson</title>

<script src="libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="libs/bootstrap-3.3.5/css/spacelab.min.css" rel="stylesheet" />
<script src="libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="libs/navigation-1.1/tabsets.js"></script>
<link href="libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>



<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Régression de Poisson</h1>
<h4 class="date"><br/>9 novembre 2020</h4>

</div>


<div id="objectifs" class="section level1">
<h1>Objectifs</h1>
<ul>
<li><p>Savoir quand et comment utiliser un modèle linéaire généralisé avec distribution de Poisson.</p></li>
<li><p>Détecter la surdispersion dans un modèle linéaire généralisé.</p></li>
<li><p>Adapter l’estimation de paramètres et la sélection de modèles au cas de modèles surdispersés.</p></li>
</ul>
</div>
<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>Au dernier cours, nous avons appliqué la régression logistique à l’analyse de données binaires et binomiales. Dans ce cours-ci, nous verrons un autre type de modèle linéaire généralisé, la régression de Poisson, qui sert à modéliser le nombre d’observations d’un certain événement dans une unité d’échantillonnage définie.</p>
<p>Voici quelques exemples de ce type de données en écologie:</p>
<ul>
<li>le nombre de semis d’une espèce dans plusieurs quadrats;</li>
<li>le nombre d’espèces (richesse spécifique) observé sur différents sites;</li>
<li>le nombre d’individus d’une espèce d’oiseau entendus dans un certain laps de temps lors de différentes visites à un site.</li>
</ul>
<p>Ou dans d’autres domaines:</p>
<ul>
<li>le nombre de patients arrivant à l’urgence par heure;</li>
<li>le nombre de voitures traversant une intersection par minute.</li>
</ul>
<div id="propriétés-des-données-de-comptage" class="section level2">
<h2>Propriétés des données de comptage</h2>
<ul>
<li><p>Les données de comptage sont des nombres discrets <span class="math inline">\(\ge\)</span> 0; on peut avoir 0, 1, 2, … observations, mais pas -1 ou 1.5.</p></li>
<li><p>Lorsque le nombre moyen d’observations est petit, la distribution des observations est généralement asyémtrique (ex.: si la moyenne est de 1, certains sites en auront plus que 2, mais jamais sous 0).</p></li>
<li><p>La variance du nombre d’observations tend à augmenter avec la moyenne: par exemple, si on observe en moyenne 1 espèce de champignon par placette de 10x10m, les observations varieront peut-être entre 0 et 3, mais si on en observe en moyenne 10, les observations pourraient varier entre 6 et 15.</p></li>
</ul>
<p>Ces propriétés justifient l’utilisation d’une distribution différente de la normale pour modéliser la réponse observée: la distribution de Poisson.</p>
</div>
<div id="distribution-de-poisson" class="section level2">
<h2>Distribution de Poisson</h2>
<p>Supposons que la réponse <span class="math inline">\(y\)</span> représente le nombre d’observations d’un événement dans un intervalle donné (intervalle de temps, de longueur, de surface, etc.). Supposons de plus que ces événements sont indépendants, c’est-à-dire que l’observation d’un premier événement n’influence pas la probabilité d’en observer ou non un deuxième.</p>
<p>Dans ce cas, la variable <span class="math inline">\(y\)</span> suit une distribution de Poisson, avec un paramètre <span class="math inline">\(\lambda\)</span> représentant le taux moyen d’observations par intervalle. La probabilité d’une certaine valeur de <span class="math inline">\(y\)</span> en fonction de <span class="math inline">\(\lambda\)</span> est donnée par l’équation suivante.</p>
<p><span class="math display">\[ P(y | \lambda) = \frac{\lambda^y}{y!} e^{-\lambda} \]</span></p>
<p>La distribution de Poisson n’a qu’un paramètre: <span class="math inline">\(\lambda\)</span> correspond à la fois à sa moyenne et à sa variance (donc l’écart-type est <span class="math inline">\(\sqrt{\lambda}\)</span>).</p>
<p>Dans R, la fonction <code>rpois</code> permet de générer des données suivant une distribution de Poisson et <code>dpois</code> donne la probabilité d’une valeur de <span class="math inline">\(y\)</span> donnée selon l’équation ci-dessus.</p>
<pre class="r"><code># Diagramme à barres de 10000 valeurs aléatoires tirées 
# de la distribution de Poisson avec lambda = 3
ggplot(NULL, aes(x = rpois(10000, 3))) +
    geom_bar()</code></pre>
<p><img src="10-Regression_Poisson_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<pre class="r"><code># Probabilité d&#39;obtenir y = 1 si lambda = 3
dpois(1, 3)</code></pre>
<pre><code>## [1] 0.1493612</code></pre>
</div>
<div id="comparaison-avec-la-distribution-binomiale" class="section level2">
<h2>Comparaison avec la distribution binomiale</h2>
<p>Pour la distribution binomiale, nous avions une réponse positive ou négative pour chaque individu (ou unité d’échantillonnage) et nous essayions de prédire la probabilité d’une réponse positive <span class="math inline">\(p\)</span>.</p>
<p>Dans la distribution de Poisson, la réponse est le nombre d’observations par unité d’échantillonnage et nous essayons de prédire la moyenne de ce nombre.</p>
<p>Si on a une réponse binomiale qui est rare au niveau individuel (<span class="math inline">\(p\)</span> est petit) et que la population <span class="math inline">\(n\)</span> est grande, alors on peut modéliser le nombre de cas au niveau de la population par une distribution de Poisson avec <span class="math inline">\(\lambda = np\)</span>.</p>
<p><strong>Exemple</strong>: Nous étudions une forêt de bouleaux où le chaga est présent sur une petite proportion (ex.: ~1%) des arbres. Au lieu de compter les bouleaux affectés et non-affectés par le chaga, on pourrait seulement compter le nombre de chancres de chaga dans des placettes de taille donnée et modéliser ce nombre avec une distribution de Poisson.</p>
</div>
<div id="comparaison-avec-la-distribution-normale" class="section level2">
<h2>Comparaison avec la distribution normale</h2>
<p>Lorsque <span class="math inline">\(\lambda\)</span> est assez grand, la distribution de Poisson devient plus symétrique et tend vers une distribution normale.</p>
<p><img src="10-Regression_Poisson_files/figure-html/unnamed-chunk-2-1.png" width="576" /></p>
<p>Autrement dit, si le nombre moyen est assez grand, le nombre d’observations se comporte presque comme une variable continue suivant une distribution normale avec <span class="math inline">\(\mu = \lambda\)</span>.</p>
<p>Dans ce cas, la régression linéaire pourrait s’appliquer. Toutefois, il faut se rappeler que les deux modèles font différentes suppositions au sujet de la variance de la réponse. Dans le modèle de régression linéaire, la moyenne <span class="math inline">\(\mu\)</span> dépend des prédicteurs, mais la variance <span class="math inline">\(\sigma^2\)</span> est constante. Dans le modèle de régression de Poisson, la moyenne et la variance dépendent des prédicteurs, parce qu’elles sont toutes deux égales à <span class="math inline">\(\lambda\)</span>. Il faudra donc observer les graphiques de résidus pour déterminer quel modèle est le plus approprié.</p>
</div>
<div id="indépendance-des-observations-et-surdispersion" class="section level2">
<h2>Indépendance des observations et surdispersion</h2>
<p>Tel que mentionné plus haut, la distribution de Poisson suppose l’indépendance des observations individuelles. Il est rare que cette condition soit parfaitement respectée dans la nature. Par exemple:</p>
<ul>
<li>la probabilité d’observer un semis d’une espèce augmente à proximité d’autres semis (agglomération) si les semences sont dispersées en groupes près du parent;</li>
<li>l’observation d’une espèce sur une placette affecte la probabilité d’en observer d’autres en fonction des relations de compétition ou de facilitation entre ces espèces.</li>
</ul>
<p>Le non-respect des suppositions de la distribution de Poisson peut notamment mener à une <strong>surdispersion</strong> des observations, c’est-à-dire qu’on observe plus de valeurs extrêmes que prévu par le modèle de Poisson. Dans le premier exemple ci-dessus, l’agglomération fait qu’on a davantage de placettes avec 0 semis et davantage de placettes avec un grand nombre de semis.</p>
<p>Dans le graphique ci-dessous, les barres en rouge suivent une distribution de Poisson tandis que celles en bleu représentent un cas de surdispersion. La moyenne de <span class="math inline">\(y\)</span> est de 5 dans les deux cas.</p>
<p><img src="10-Regression_Poisson_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>Nous verrons plus loin comment identifier et traiter les cas de surdispersion.</p>
</div>
</div>
<div id="régression-de-poisson" class="section level1">
<h1>Régression de Poisson</h1>
<p>La régression de Poisson est un modèle linéaire généralisé où la réponse <span class="math inline">\(y\)</span> suit une distribution de Poisson:</p>
<p><span class="math display">\[ y \sim Pois(\lambda) \]</span></p>
<p>Puisque <span class="math inline">\(\lambda\)</span> doit être un nombre positif, nous utiliserons la fonction de logarithme comme lien avec le prédicteur linéaire.</p>
<p><span class="math display">\[ \log{\lambda} = \eta = \beta_0 + \sum_{i = 1}^m \beta_i x_i \]</span></p>
<p>Selon les propriétés de la fonction log, une valeur de 0 du prédicteur <span class="math inline">\(\eta\)</span> correspond à <span class="math inline">\(\lambda = 1\)</span>, une valeur positive correspond à <span class="math inline">\(\lambda &gt; 1\)</span> et une valeur négative à <span class="math inline">\(\lambda &lt; 1\)</span>.</p>
<p><img src="10-Regression_Poisson_files/figure-html/unnamed-chunk-4-1.png" width="384" /></p>
<p>En inversant le log, on obtient une relation exponentielle entre la réponse moyenne <span class="math inline">\(\lambda\)</span> et les prédicteurs:</p>
<p><span class="math display">\[ \hat{y} = \lambda = e^{\beta_0 + \sum_{i = 1}^m \beta_i x_i} \]</span></p>
<p>Puisque l’addition de puissances correspond à une multiplication, ce modèle correspond à des effets multiplicatifs des prédicteurs sur la réponse.</p>
<p><span class="math display">\[ \hat{y} = e^{\beta_0} e^{\beta_1 x_1} e^{\beta_2 x_2} \ldots \]</span></p>
<p>Le logarithme est la fonction de lien par défaut pour la régression de Poisson. Pour bien interpréter les résultats de la régression, il faut se rappeler qu’une transformation logarithmique est appliquée à la réponse moyenne.</p>
<div id="résumé-des-modèles-linéaires-généralisés-vu-dans-ce-cours" class="section level2">
<h2>Résumé des modèles linéaires généralisés vu dans ce cours</h2>
<table>
<colgroup>
<col width="12%" />
<col width="25%" />
<col width="30%" />
<col width="30%" />
</colgroup>
<thead>
<tr class="header">
<th>Modèle</th>
<th>Distribution</th>
<th>Lien par défaut</th>
<th>Inverse du lien</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Régression linéaire</td>
<td>Normale: <span class="math inline">\(y \sim N(\mu, \sigma)\)</span></td>
<td>Identité: <span class="math inline">\(\mu = \eta\)</span></td>
<td><span class="math inline">\(\mu = \eta\)</span></td>
</tr>
<tr class="even">
<td>Régression logistique</td>
<td>Binomiale: <span class="math inline">\(y \sim B(n, p)\)</span></td>
<td>Logit: <span class="math inline">\(\log(p/(1-p)) = \eta\)</span></td>
<td><span class="math inline">\(p = 1/(1+e^{-\eta})\)</span></td>
</tr>
<tr class="odd">
<td>Régression de Poisson</td>
<td>Poisson: <span class="math inline">\(y \sim Pois(\lambda)\)</span></td>
<td>Log: <span class="math inline">\(\log(\lambda) = \eta\)</span></td>
<td><span class="math inline">\(\lambda = e^{\eta}\)</span></td>
</tr>
</tbody>
</table>
</div>
<div id="exemple" class="section level2">
<h2>Exemple</h2>
<p>Le fichier <a href="../donnees/species.csv">species.csv</a> contient un tableau de données présentant le nombre d’espèces de plantes dans différents quadrats (<code>Species</code>) en fonction de la biomasse totale du quadrat (<code>Biomass</code>) et du pH codé selon trois niveaux (faible, moyen, élevé).</p>
<pre class="r"><code>sp &lt;- read.csv(&quot;../donnees/species.csv&quot;) 
# Niveaux de pH dans le bon ordre
sp$pH &lt;- factor(sp$pH, levels = c(&quot;low&quot;, &quot;mid&quot;, &quot;high&quot;))
str(sp)</code></pre>
<pre><code>## &#39;data.frame&#39;:    90 obs. of  3 variables:
##  $ pH     : Factor w/ 3 levels &quot;low&quot;,&quot;mid&quot;,&quot;high&quot;: 3 3 3 3 3 3 3 3 3 3 ...
##  $ Biomass: num  0.469 1.731 2.09 3.926 4.367 ...
##  $ Species: int  30 39 44 35 25 29 23 18 19 12 ...</code></pre>
<p>Regardons la distribution de la réponse en fonction des prédicteurs:</p>
<pre class="r"><code>ggplot(sp, aes(x = Biomass, y = Species)) +
    geom_point()</code></pre>
<p><img src="10-Regression_Poisson_files/figure-html/unnamed-chunk-6-1.png" width="384" /></p>
<pre class="r"><code>ggplot(sp, aes(x = pH, y = Species)) +
    geom_boxplot()</code></pre>
<p><img src="10-Regression_Poisson_files/figure-html/unnamed-chunk-6-2.png" width="384" /></p>
<p>Sur ces graphiques, nous remarquons que les conditions associées à un plus grand nombre moyen d’espèces (biomasse faible, pH élevé) ont aussi une plus grande variance. Cela suggère qu’une régression de Poisson pourrait être appropriée.</p>
<p>Comme pour la régression logistique, la régression de Poisson utilise la fonction <code>glm</code>. Il faut spécifier la famille <code>poisson</code> et (optionnellement) le lien log.</p>
<pre class="r"><code>mod_sp &lt;- glm(Species ~ Biomass + pH, sp, family = poisson(link = &quot;log&quot;))
summary(mod_sp)</code></pre>
<pre><code>## 
## Call:
## glm(formula = Species ~ Biomass + pH, family = poisson(link = &quot;log&quot;), 
##     data = sp)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.5959  -0.6989  -0.0737   0.6647   3.5604  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  2.71255    0.05713   47.48   &lt;2e-16 ***
## Biomass     -0.12756    0.01014  -12.58   &lt;2e-16 ***
## pHmid        0.69123    0.06815   10.14   &lt;2e-16 ***
## pHhigh       1.13639    0.06720   16.91   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 452.346  on 89  degrees of freedom
## Residual deviance:  99.242  on 86  degrees of freedom
## AIC: 526.43
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>Avant d’interpréter les coefficients, vérifions l’ajustement du modèle avec les graphiques de diagnostic.</p>
<p><img src="10-Regression_Poisson_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>Le premier graphique montre une tendance au niveau des résidus (résidus plus négatifs aux extrêmes et plus positifs au centre). Vu le nombre de points, cette tendance n’est probablement pas due au hasard mais représente un effet systématique qui n’est pas pris en compte dans ce modèle.</p>
<p>Essayons donc un modèle plus complexe ou il y a interaction entre l’effet de la biomasse et du pH.</p>
<pre class="r"><code>mod_sp_inter &lt;- glm(Species ~ Biomass * pH, sp, family = poisson)</code></pre>
<p><img src="10-Regression_Poisson_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>Sans avoir éliminé complètement la tendance, cet ajustement semble bien meilleur.</p>
<p><strong>Note</strong>: Dans ce cas-ci, ces résidus s’approchent de la normalité (d’après le diagramme quantile-quantile) car les valeurs observées de la réponse sont assez élevées (nombre moyen de 20 espèces par quadrat). Nous avions la même situation pour la régression logistique binomiale lorsque <span class="math inline">\(n\)</span> était élevé. Toutefois, nous ne nous attendons pas à ce que le diagramme quantile-quantile montre une droite si <span class="math inline">\(\lambda\)</span> est petit, même si le modèle de Poisson s’applique parfaitement.</p>
<p>Regardons maintenant le sommaire du modèle.</p>
<pre class="r"><code>summary(mod_sp_inter)</code></pre>
<pre><code>## 
## Call:
## glm(formula = Species ~ Biomass * pH, family = poisson, data = sp)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.4978  -0.7485  -0.0402   0.5575   3.2297  
## 
## Coefficients:
##                Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)     2.95255    0.08240  35.833  &lt; 2e-16 ***
## Biomass        -0.26216    0.03803  -6.893 5.47e-12 ***
## pHmid           0.48411    0.10723   4.515 6.34e-06 ***
## pHhigh          0.81557    0.10284   7.931 2.18e-15 ***
## Biomass:pHmid   0.12314    0.04270   2.884 0.003927 ** 
## Biomass:pHhigh  0.15503    0.04003   3.873 0.000108 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 452.346  on 89  degrees of freedom
## Residual deviance:  83.201  on 84  degrees of freedom
## AIC: 514.39
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>L’AIC de ce modèle est égal à 514 comparé à 526 pour le modèle sans interaction, ce qui confirme le meilleur ajustement. Le pseudo-<span class="math inline">\(R^2\)</span> est aussi élevé (1 - 83/452 = 0.82).</p>
<p>Voici un graphique montrant la superposition des valeurs attendues de la réponse (courbes tracées à partir des valeurs <code>fitted(mod_sp_inter)</code>) et des valeurs observées (points) en fonction de la biomasse et du pH.</p>
<pre class="r"><code>ggplot(sp, aes(x = Biomass, y = Species, color = pH)) +
    geom_point() +
    geom_line(aes(y = fitted(mod_sp_inter))) +
    scale_color_brewer(palette = &quot;Dark2&quot;)</code></pre>
<p><img src="10-Regression_Poisson_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
</div>
<div id="interprétation-des-coefficients" class="section level2">
<h2>Interprétation des coefficients</h2>
<p>L’interprétation des coefficients du modèle est plus complexe avec les interactions, donc commençons avec le modèle sans interaction.</p>
<pre class="r"><code>summary(mod_sp)</code></pre>
<pre><code>## 
## Call:
## glm(formula = Species ~ Biomass + pH, family = poisson(link = &quot;log&quot;), 
##     data = sp)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.5959  -0.6989  -0.0737   0.6647   3.5604  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  2.71255    0.05713   47.48   &lt;2e-16 ***
## Biomass     -0.12756    0.01014  -12.58   &lt;2e-16 ***
## pHmid        0.69123    0.06815   10.14   &lt;2e-16 ***
## pHhigh       1.13639    0.06720   16.91   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 452.346  on 89  degrees of freedom
## Residual deviance:  99.242  on 86  degrees of freedom
## AIC: 526.43
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>Il est plus facile de déterminer d’abord l’effet de chaque coefficient du modèle sur le prédicteur linéaire: <span class="math inline">\(\eta = \beta_0 + \sum_{i=1}^{m} \beta_i x_i\)</span>, puis de déduire l’effet sur la moyenne de la réponse (<span class="math inline">\(\lambda\)</span>) à partir de la fonction <span class="math inline">\(\lambda = e^{-\eta}\)</span>.</p>
<p>Par exemple, l’ordonnée à l’origine indique que dans le cas où la biomasse est 0 et le pH est bas (niveau de référence), <span class="math inline">\(\eta = 2.71\)</span> et donc <span class="math inline">\(\lambda = e^{-\eta} = 15.0\)</span> espèces. Bien sûr, cette valeur n’est pas réaliste car il ne peut pas y avoir d’espèces sans biomasse.</p>
<p>Pour les autres paramètres:</p>
<ul>
<li><p>Le coefficient <code>Biomass</code> indique que <span class="math inline">\(\eta\)</span> diminue de 0.13 pour chaque augmentation d’une unité de biomasse, si les autres variables (donc le pH) restent constantes. Un changement additif de -0.13 sur l’échelle logarithmique correspond à un changement multiplicatif de <span class="math inline">\(e^{-0.13} = 0.88\)</span>, soit une perte de 12% du nombre moyen d’espèces par unité de biomasse supplémentaire.</p></li>
<li><p>Le coefficient de <code>pHmid</code> indique que lorsqu’on passe d’un niveau bas à moyen de pH (pour la même biomasse), <span class="math inline">\(\eta\)</span> augmente de 0.69. Puisque <span class="math inline">\(e^{0.69} = 2.0\)</span>, le nombre moyen d’espèces à un pH moyen est le double de celui à un pH bas.</p></li>
<li><p>De même, le coefficient de <code>pHhigh</code> indique que le nombre moyen d’espèces est multiplié par <span class="math inline">\(e^{1.14} = 3.13\)</span> si on passe d’un pH bas à un pH élevé pour la même biomasse.</p></li>
</ul>
<p>En résumé, dans le cas où il n’y a pas d’interactions, les effets sont additifs sur l’échelle du prédicteur linéaire. Le coefficient <span class="math inline">\(\beta_i\)</span> de la variable <span class="math inline">\(x_i\)</span> indique qu’une augmentation de 1 unité de <span class="math inline">\(x_i\)</span>, en maintenant les valeurs des autres variables, résulte en une <em>multiplication</em> de la réponse moyenne par <span class="math inline">\(e^{\beta_i}\)</span>.</p>
<p>Regardons maintenant le cas de l’interaction:</p>
<pre class="r"><code>summary(mod_sp_inter)</code></pre>
<pre><code>## 
## Call:
## glm(formula = Species ~ Biomass * pH, family = poisson, data = sp)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.4978  -0.7485  -0.0402   0.5575   3.2297  
## 
## Coefficients:
##                Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)     2.95255    0.08240  35.833  &lt; 2e-16 ***
## Biomass        -0.26216    0.03803  -6.893 5.47e-12 ***
## pHmid           0.48411    0.10723   4.515 6.34e-06 ***
## pHhigh          0.81557    0.10284   7.931 2.18e-15 ***
## Biomass:pHmid   0.12314    0.04270   2.884 0.003927 ** 
## Biomass:pHhigh  0.15503    0.04003   3.873 0.000108 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 452.346  on 89  degrees of freedom
## Residual deviance:  83.201  on 84  degrees of freedom
## AIC: 514.39
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>Dans le modèle avec interaction, l’effet du pH dépend de la biomasse et vice versa. Considérerons donc séparément les trois niveaux de pH; pour simplifier, l’effet “biomasse = 0” sera indiqué même si ce n’est pas un niveau réaliste de la variable.</p>
<ul>
<li><p>À pH bas, nous avons: <span class="math inline">\(\eta = 2.95 - 0.26 \times \text{biomasse}\)</span>. Donc, le nombre d’espèce moyen est de <span class="math inline">\(e^{2.95} = 19\)</span> pour une biomasse de 0 et diminue de 23% (<span class="math inline">\(e^{-0.26} = 0.77\)</span>) par unité de biomasse.</p></li>
<li><p>À pH moyen, nous avons: <span class="math inline">\(\eta = (2.95 + 0.48) + (-0.26 + 0.12) \times \text{biomasse}\)</span>, ou <span class="math inline">\(\eta = 3.43 - 0.14 \times \text{biomasse}\)</span>. Donc, le nombre d’espèce moyen est de 30.9 pour une biomasse de 0 et diminue de 13% par unité de biomasse.</p></li>
<li><p>À pH élevé, nous avons: <span class="math inline">\(\eta = (2.95 + 0.82) + (-0.26 + 0.16) \times \text{biomasse}\)</span>, équivalent à un nombre d’espèces moyen de 43.4 pour une biomasse de 0 et une diminution de 10% par unité de biomasse.</p></li>
</ul>
<p>Pour une interaction entre une variable numérique et une variable catégorielle, il est plus simple de décrire les effets pour chaque niveau de la variable catégorielle, comme nous venons de faire. Pour une interaction entre deux variables numériques, nous pouvons visualiser les effets à partir des courbes de valeurs prédites, mais il devient compliqué d’interpréter les coefficients individuels.</p>
</div>
</div>
<div id="surdispersion" class="section level1">
<h1>Surdispersion</h1>
<p>Le sommaire des résultats des régressions de Poisson effectuées dans la partie précédente incluait le message: <code>(Dispersion parameter for poisson family taken to be 1)</code>. Ce message nous rappelle que la variance des observations n’est pas estimée de façon indépendante dans ce modèle (contrairement au modèle de régression linéaire), mais égale à la valeur moyenne <span class="math inline">\(\lambda\)</span> estimée en fonction des prédicteurs pour chaque point.</p>
<p>Tel qu’il a été mentionné dans l’introduction, la non-indépendance des observations individuelles peut causer une surdispersion des données par rapport aux suppositions de la distribution de Poisson. Cette surdispersion est représentée par un paramètre <span class="math inline">\(\phi\)</span> qui multiplie la variance attendue: pour une moyenne <span class="math inline">\(\lambda\)</span>, la variance devient donc <span class="math inline">\(\phi \lambda\)</span>.</p>
<p>De façon moins fréquente, il arrive que <span class="math inline">\(\phi &lt; 1\)</span>, correspondant à une <em>sous-dispersion</em> des observations. Contrairement à la surdispersion, où les observations tendent à être regroupées (ex.: quelques quadrats avec de nombreux individus, et plusieurs avec peu ou pas d’individus), la sous-dispersion signifie que les observations sont réparties de façon plus régulière que prévue. Cela pourrait être dû par exemple à la compétition intraspécifique ou à la territorialité (dans le cas d’animaux) qui mène les individus à s’espacer de façon régulière.</p>
<div id="estimation-du-paramètre-de-dispersion" class="section level2">
<h2>Estimation du paramètre de dispersion</h2>
<p>Pour détecter la présente de surdispersion ou de sous-dispersion, nous utiliserons la statistique du <span class="math inline">\(\chi^2\)</span>, qui a déjà été vue dans le contexte des tableaux de contingence. Cette statistique est calculée à partir des écarts carrés entre les valeurs observées <span class="math inline">\(y\)</span> et attendues <span class="math inline">\(\hat{y}\)</span>, normalisés par la valeur attendue, pour chacun des <span class="math inline">\(n\)</span> points du jeu de données.</p>
<p><span class="math display">\[ \chi^2 = \sum_{k=1}^n \frac{(y_k - \hat{y_k})^2}{\hat{y_k}} \]</span></p>
<p>Si les données suivent la distribution de Poisson, la valeur moyenne du <span class="math inline">\(\chi^2\)</span> est égale au nombre de degrés de liberté résiduels du modèle: <span class="math inline">\(df_{res} = n - p\)</span>, où <span class="math inline">\(p\)</span> est le nombre de paramètres estimés. Pour estimer le paramètre de dispersion <span class="math inline">\(\phi\)</span>, nous utiliserons donc l’estimateur:</p>
<p><span class="math display">\[ \hat{c} = \frac{\chi^2}{df_{res}} \]</span></p>
<p>Pour le modèle avec interactions, nous obtenons presque exactement la valeur théorique de 1:</p>
<pre class="r"><code>chisq &lt;- sum((sp$Species - fitted(mod_sp_inter))^2/fitted(mod_sp_inter))
chisq/mod_sp_inter$df.residual</code></pre>
<pre><code>## [1] 0.9970014</code></pre>
<p>Pour le modèle sans interaction, nous détectons une légère surdispersion:</p>
<pre class="r"><code>chisq &lt;- sum((sp$Species - fitted(mod_sp))^2/fitted(mod_sp))
chisq/mod_sp$df.residual</code></pre>
<pre><code>## [1] 1.10675</code></pre>
<p>Pour déterminer si le <span class="math inline">\(\chi^2\)</span> diffère significativement de la valeur attendue selon la distribution de Poisson, nous pouvons calculer la probabilité d’avoir obtenu un <span class="math inline">\(\chi^2\)</span> plus élevé si le modèle est correct.</p>
<pre class="r"><code>1 - pchisq(chisq, df = mod_sp$df.residual)</code></pre>
<pre><code>## [1] 0.2336238</code></pre>
<p>Dans ce cas, la surdispersion n’est pas significative, il n’est donc pas nécessaire d’ajuster les résultats du modèle.</p>
</div>
<div id="exemple-de-données-surdispersées" class="section level2">
<h2>Exemple de données surdispersées</h2>
<p>Le tableau de données <a href="../donnees/galapagos.csv">galapagos.csv</a> donne le nombre d’espèces de tortues (<code>Species</code>) et le nombre d’espèces endémiques (<code>Endemics</code>) pour différentes îles de l’archipel des Galapagos en fonction de leur superficie (<code>Area</code>), de leur altitude moyenne (<code>Elevation</code>), de la superficie de l’île la plus près (<code>Adjacent</code>), de la distance à l’île la plus près (<code>Nearest</code>) et de la distance à l’île de Santa Cruz (<code>Scruz</code>).</p>
<pre class="r"><code>glp &lt;- read.csv(&quot;../donnees/galapagos.csv&quot;)
str(glp)</code></pre>
<pre><code>## &#39;data.frame&#39;:    30 obs. of  8 variables:
##  $ Name     : chr  &quot;Baltra&quot; &quot;Bartolome&quot; &quot;Caldwell&quot; &quot;Champion&quot; ...
##  $ Species  : int  58 31 3 25 2 18 24 10 8 2 ...
##  $ Endemics : int  23 21 3 9 1 11 0 7 4 2 ...
##  $ Area     : num  25.09 1.24 0.21 0.1 0.05 ...
##  $ Elevation: int  346 109 114 46 77 119 93 168 71 112 ...
##  $ Nearest  : num  0.6 0.6 2.8 1.9 1.9 8 6 34.1 0.4 2.6 ...
##  $ Scruz    : num  0.6 26.3 58.7 47.4 1.9 ...
##  $ Adjacent : num  1.84 572.33 0.78 0.18 903.82 ...</code></pre>
<p>Supposons que nous voulons déterminer comment le nombre d’espèces de tortues endémiques (celles présentent sur une seule île) varie en fonction des prédicteurs <code>Area</code>, <code>Elevation</code>, <code>Nearest</code> et <code>Adjacent</code>. Puisque chacun de ces prédicteurs est distribué de façon très asymétrique (voir l’exemple ci-dessous pour la superficie), nous utiliserons le logarithme de chaque prédicteur.</p>
<p><img src="10-Regression_Poisson_files/figure-html/unnamed-chunk-19-1.png" width="576" /></p>
<p>Nous ajustons le modèle suivant dans R. Notez que la réponse est <code>Endemics</code> et non <code>log(Endemics)</code>, car le lien log est inclus dans le modèle <code>glm</code> avec distribution de Poisson.</p>
<pre class="r"><code>mod_glp &lt;- glm(Endemics ~ log(Area) + log(Elevation) + log(Nearest) + log(Adjacent), 
               data = glp, family = poisson)</code></pre>
<p>Les graphiques de diagnostic indiquent la présence de quelques valeurs extrêmes, bien qu’aucune des distances de Cook soit &gt;1.</p>
<pre class="r"><code>par(mfrow = c(2,2))
plot(mod_glp)</code></pre>
<p><img src="10-Regression_Poisson_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<pre class="r"><code>par(mfrow = c(1, 1))</code></pre>
<p>Le modèle indique des effets significatifs pour 3 paramètres: le nombre d’espèces endémiques augmente avec la superficie de l’île; il diminue en fonction de la distance à l’île la plus près et de la superficie de cette île la plus près.</p>
<pre class="r"><code>summary(mod_glp)</code></pre>
<pre><code>## 
## Call:
## glm(formula = Endemics ~ log(Area) + log(Elevation) + log(Nearest) + 
##     log(Adjacent), family = poisson, data = glp)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -3.4411  -1.7215   0.0330   0.7395   3.8476  
## 
## Coefficients:
##                Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)     2.47684    0.45817   5.406 6.45e-08 ***
## log(Area)       0.27504    0.02922   9.414  &lt; 2e-16 ***
## log(Elevation)  0.01251    0.09251   0.135  0.89243    
## log(Nearest)   -0.06128    0.02118  -2.894  0.00381 ** 
## log(Adjacent)  -0.04576    0.01099  -4.162 3.15e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 743.55  on 29  degrees of freedom
## Residual deviance:  95.66  on 25  degrees of freedom
## AIC: 238.61
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>Toutefois, en faisant le test du <span class="math inline">\(\chi^2\)</span>, nous notons que les données sont surdispersées.</p>
<pre class="r"><code>chisq &lt;- sum((glp$Endemics - fitted(mod_glp))^2/fitted(mod_glp))
1 - pchisq(chisq, df = mod_glp$df.residual)</code></pre>
<pre><code>## [1] 1.109039e-09</code></pre>
<pre class="r"><code>disp &lt;- chisq/mod_glp$df.residual
disp</code></pre>
<pre><code>## [1] 3.700441</code></pre>
<p>L’estimé du paramètre de dispersion est égal à 3.7. Lorsque <span class="math inline">\(\hat{c}\)</span> n’est pas trop élevé (typiquement, on suggère <span class="math inline">\(\hat{c} &lt; 4\)</span>), les estimés des coefficients de la régression de Poisson demeurent valides, mais il faut multiplier leurs erreurs-types par <span class="math inline">\(\sqrt{\hat{c}}\)</span>. Autrement dit, la surdispersion n’introduit pas de biais, mais augmente l’incertitude sur les valeurs des coefficients. Si la surdispersion est très grande, il est préférable d’utiliser un autre modèle.</p>
<p>Pour corriger les erreurs-types, il suffit d’ajouter un argument <code>dispersion</code> au moment d’appeler la fonction <code>summary</code>:</p>
<pre class="r"><code>summary(mod_glp, dispersion = disp)</code></pre>
<pre><code>## 
## Call:
## glm(formula = Endemics ~ log(Area) + log(Elevation) + log(Nearest) + 
##     log(Adjacent), family = poisson, data = glp)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -3.4411  -1.7215   0.0330   0.7395   3.8476  
## 
## Coefficients:
##                Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)     2.47684    0.88137   2.810  0.00495 ** 
## log(Area)       0.27504    0.05620   4.894 9.89e-07 ***
## log(Elevation)  0.01251    0.17796   0.070  0.94396    
## log(Nearest)   -0.06128    0.04074  -1.504  0.13251    
## log(Adjacent)  -0.04576    0.02115  -2.164  0.03049 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 3.700441)
## 
##     Null deviance: 743.55  on 29  degrees of freedom
## Residual deviance:  95.66  on 25  degrees of freedom
## AIC: 238.61
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>De façon équivalente, on peut utiliser la famille <code>quasipoisson</code> qui effectue automatiquement l’estimation du paramètre de dispersion.</p>
<pre class="r"><code>mod_quasi &lt;- glm(Endemics ~ log(Area) + log(Elevation) + log(Nearest) + log(Adjacent), 
               data = glp, family = quasipoisson)
summary(mod_quasi)</code></pre>
<pre><code>## 
## Call:
## glm(formula = Endemics ~ log(Area) + log(Elevation) + log(Nearest) + 
##     log(Adjacent), family = quasipoisson, data = glp)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -3.4411  -1.7215   0.0330   0.7395   3.8476  
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     2.47684    0.88137   2.810  0.00948 ** 
## log(Area)       0.27504    0.05620   4.894 4.91e-05 ***
## log(Elevation)  0.01251    0.17796   0.070  0.94451    
## log(Nearest)   -0.06128    0.04074  -1.504  0.14504    
## log(Adjacent)  -0.04576    0.02115  -2.164  0.04025 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for quasipoisson family taken to be 3.700441)
## 
##     Null deviance: 743.55  on 29  degrees of freedom
## Residual deviance:  95.66  on 25  degrees of freedom
## AIC: NA
## 
## Number of Fisher Scoring iterations: 5</code></pre>
</div>
<div id="paramètre-de-dispersion-pour-la-famille-binomiale" class="section level2">
<h2>Paramètre de dispersion pour la famille binomiale</h2>
<p>Pour une régression ou la réponse est binomiale (nombre de succès <span class="math inline">\(y\)</span> et d’échecs <span class="math inline">\(n - y\)</span>), les réponses peuvent aussi être surdispersées ou sous-dispersées. Dans ce cas, on estime le paramètre de dispersion de la même façon avec la statistique du <span class="math inline">\(\chi^2\)</span>. On peut aussi utiliser la famille <code>quasibinomial</code> avec la fonction <code>glm</code>.</p>
<p>Pour une réponse binaire (0 ou 1), le concept de paramètre de dispersion ne s’applique pas, car la variance est toujours <span class="math inline">\(p(1-p)\)</span>.</p>
</div>
<div id="sélection-de-modèles-avec-surdispersion" class="section level2">
<h2>Sélection de modèles avec surdispersion</h2>
<p>En plus d’augmenter l’erreur-type des coefficients du modèle, la surdispersion affecte aussi la sélection de modèles avec l’AIC. Le QAIC, l’équivalent de l’AIC pour les modèles de type quasibinomial ou quasipoisson, est calculé en divisant le premier terme de l’AIC par l’estimé du paramètre de dispersion.</p>
<p><span class="math display">\[ QAIC = -\frac{2 \log L}{\hat{c}} + 2 K \]</span></p>
<p>On peut modifier l’AICc de la même façon pour obtenir le QAICc.</p>
<p><span class="math display">\[ QAICc = -\frac{2 \log L}{\hat{c}} + 2 K \left( \frac{n}{n-K-1} \right) \]</span></p>
<p>Le <span class="math inline">\(\hat{c}\)</span> compte lui-même comme un paramètre estimé, donc la valeur de <span class="math inline">\(K\)</span> augmente aussi de 1 par rapport au modèle sans surdispersion.</p>
<p>Si on compare plusieurs modèles avec le QAIC ou QIACc, il faut utiliser une seule valeur du <span class="math inline">\(\hat{c}\)</span>, celle calculée à partir du modèle le plus complexe. Cette valeur est fournie aux fonctions du package (par exemple, <code>aictab</code>) avec l’argument <code>c.hat</code>.</p>
<p>Par exemple, considérons les quatres modèles suivants pour prédire le nombre d’espèces endémiques sur les îles Galapagos.</p>
<pre class="r"><code>mod_area &lt;- glm(Endemics ~ log(Area), data = glp, family = poisson)
mod_area_near &lt;- glm(Endemics ~ log(Area) + log(Nearest), data = glp, family = poisson)
mod_area_adj &lt;- glm(Endemics ~ log(Area) + log(Adjacent), data = glp, family = poisson)
mod_comp &lt;- glm(Endemics ~ log(Area) + log(Nearest) + log(Adjacent), data = glp, family = poisson)</code></pre>
<p>Remarquez que nous utilisons la famille <code>poisson</code> plutôt que <code>quasipoisson</code>; nous laisserons la fonction de sélection de modèles appliquer la correction. Le paramètre de dispersion du modèle complet peut être calculé avec la fonction <code>c_hat</code> de <em>AICcmodavg</em>. (Cette valeur diffère un peu de celle obtenue plus haut, car nous avons retranché le prédicteur <code>Elevation</code>.)</p>
<pre class="r"><code>library(AICcmodavg)

disp &lt;- c_hat(mod_comp)
disp</code></pre>
<pre><code>## &#39;c-hat&#39; 3.56 (method: pearson estimator)</code></pre>
<p>Voici le tableau du QAICc pour ces modèles:</p>
<pre class="r"><code>mod_list &lt;- list(mod_area = mod_area, mod_area_near = mod_area_near, 
                 mod_area_adj = mod_area_adj, mod_comp = mod_comp)
aictab(mod_list, c.hat = disp)</code></pre>
<pre><code>## 
## Model selection based on QAICc:
## (c-hat estimate = 3.562208)
## 
##               K QAICc Delta_QAICc QAICcWt Cum.Wt Quasi.LL
## mod_area_adj  4 76.19        0.00    0.42   0.42   -33.30
## mod_comp      5 76.68        0.49    0.33   0.75   -32.09
## mod_area      3 78.49        2.29    0.13   0.89   -35.78
## mod_area_near 4 78.82        2.63    0.11   1.00   -34.61</code></pre>
<p>Comparons maintenant avec la version obtenue sans tenir compte de la surdispersion:</p>
<pre class="r"><code>aictab(mod_list)</code></pre>
<pre><code>## 
## Model selection based on AICc:
## 
##               K   AICc Delta_AICc AICcWt Cum.Wt      LL
## mod_comp      4 238.23       0.00   0.95   0.95 -114.31
## mod_area_adj  3 244.14       5.91   0.05   1.00 -118.61
## mod_area_near 3 253.50      15.27   0.00   1.00 -123.29
## mod_area      2 259.37      21.14   0.00   1.00 -127.46</code></pre>
<p>Non seulement la surdispersion change l’ordre des modèles, mais elle diminue la différence entre les modèles: les <span class="math inline">\(\Delta QAICc\)</span> sont beaucoup plus rapprochés que les <span class="math inline">\(\Delta AICc\)</span>. Les quatre modèles ont un poids supérieur à 10% dans le premier cas, tandis que le premier modèle obtient 95% des poids dans le deuxième tableau. Ainsi, il y a davantage d’incertitude sur le choix d’un meilleur modele.</p>
</div>
</div>
<div id="résumé" class="section level1">
<h1>Résumé</h1>
<div id="régression-de-poisson-1" class="section level2">
<h2>Régression de Poisson</h2>
<ul>
<li><p>La distribution de Poisson représente le nombre d’observations indépendantes d’un événement dans une unité d’échantillonnage.</p></li>
<li><p>Le modèle de régression de Poisson est basé sur une distribution de Poisson de la réponse autour de sa valeur moyenne; cette valeur est reliée au prédicteur linéaire par la fonction de logarithme.</p></li>
<li><p>En raison du lien logarithmique, les effets additifs sur l’échelle du prédicteur linéaire deviennent des effets multiplicatifs sur l’échelle de la réponse.</p></li>
<li><p>Les distributions binomiale et de Poisson supposent une certaine relation entre la valeur moyenne de la réponse et sa variance. La surdispersion correspond à une variance plus grande que prévue par la distribution.</p></li>
<li><p>Si le paramètre de dispersion n’est pas trop élevé (<span class="math inline">\(\hat{c} &lt; 4\)</span>), on peut tout de même utiliser le modèle de Poisson (ou binomial) et multiplier les erreurs-types des coefficients par <span class="math inline">\(\sqrt{\hat{c}}\)</span>. Pour la sélection de modèles, l’AIC(c) doit être remplacé par le QAIC(c) pour tenir compte de la surdispersion.</p></li>
</ul>
</div>
<div id="modélisation-statistique-points-généraux-à-retenir" class="section level2">
<h2>Modélisation statistique: points généraux à retenir</h2>
<p>Nous avons étudié différents types de modèles cette session (ANOVA, régression linéaire, modèles linéaires généralisés et modèles mixtes à venir). Vous aurez peut-être remarqué que nous appliquons des étapes semblables dans chaque cas.</p>
<ul>
<li>Exploration des données (distribution des variables individuelles et corrélations);</li>
<li>Choix d’un type de modèle et ajustement du modèle (<code>lm</code>, <code>glm</code>, etc.);</li>
<li>Vérification des suppositions du modèle (ex.: graphiques de diagnostic, paramètre de dispersion);</li>
<li>Interprétation des valeurs estimées des coefficients;</li>
<li>Visualisation des prédictions du modèle;</li>
<li>Si plusieurs modèles candidats: comparaison, sélection d’un meilleur modèle et/ou prédictions multimodèles.</li>
</ul>
<p>Vous devriez être en mesure de réaliser chacune de ses étapes pour les modèles statistiques vus dans ce cours et ceux que vous appliquerez à vos travaux de recherche.</p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
