<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />



<meta name="date" content="2021-11-08" />

<title>Poisson regression</title>

<script src="libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="libs/bootstrap-3.3.5/css/spacelab.min.css" rel="stylesheet" />
<script src="libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="libs/navigation-1.1/tabsets.js"></script>
<link href="libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>



<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Poisson regression</h1>
<h4 class="date"><br/>November 8, 2021</h4>

</div>


<div id="objectives" class="section level1">
<h1>Objectives</h1>
<ul>
<li><p>Know when and how to use a generalized linear model with a Poisson distribution.</p></li>
<li><p>Detect overdispersion in a generalized linear model.</p></li>
<li><p>Adapt the estimation of parameters and the selection of models to the case of overdispersed models.</p></li>
</ul>
</div>
<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>At the last class, we applied logistic regression to the analysis of binary and binomial data. In this course, we will see another type of generalized linear model, Poisson regression, which is used to model the number of observations of a certain event in a defined sampling unit.</p>
<p>Here are some examples of this type of data in ecology:</p>
<ul>
<li>the number of seedlings of a species in several quadrats;</li>
<li>the number of species (species richness) observed at different sites;</li>
<li>the number of individuals of a species of bird heard in a certain period of time during different visits to a site.</li>
</ul>
<p>Or in other areas:</p>
<ul>
<li>the number of patients arriving at the emergency room per hour;</li>
<li>the number of cars crossing an intersection per minute.</li>
</ul>
<div id="count-data-properties" class="section level2">
<h2>Count data properties</h2>
<ul>
<li><p>The count data are discrete numbers <span class="math inline">\(\ge\)</span> 0; we can have 0, 1, 2, … observations, but not -1 or 1.5.</p></li>
<li><p>When the mean number of observations is small, the distribution of observations is generally asymmetric (e.g. if the mean is 1, some sites will have more than 2, but never 0).</p></li>
<li><p>The variance of the number of observations tends to increase with the mean: for example, if we observe a mean of 1 species of mushroom per plot of 10x10m, the observations will vary perhaps between 0 and 3, but if we observe a mean of 10, the observations could vary between 6 and 15.</p></li>
</ul>
<p>These properties justify the use of a distribution different from the normal distribution to model the observed response: the Poisson distribution.</p>
</div>
<div id="poisson-distribution" class="section level2">
<h2>Poisson distribution</h2>
<p>Suppose that the response <span class="math inline">\(y\)</span> represents the number of observations of an event in a given interval (interval of time, length, area, etc.). Suppose moreover that these events are independent, that is to say that the observation of a first event does not influence the probability of observing a second one or not.</p>
<p>In this case, the variable <span class="math inline">\(y\)</span> follows a Poisson distribution, with a parameter <span class="math inline">\(\lambda\)</span> representing the mean rate of observations per interval. The probability of a certain value of <span class="math inline">\(y\)</span> as a function of <span class="math inline">\(\lambda\)</span> is given by the following equation.</p>
<p><span class="math display">\[ P(y | \lambda) = \frac{\lambda^y}{y!} e^{-\lambda} \]</span></p>
<p>The Poisson distribution has only one parameter: <span class="math inline">\(\lambda\)</span> corresponds to both its mean and its variance (so the standard deviation is <span class="math inline">\(\sqrt{\lambda}\)</span>).</p>
<p>In R, the <code>rpois</code> function can generate data according to a Poisson distribution, and <code>dpois</code> gives the probability of a given value of <span class="math inline">\(y\)</span> according to the above equation.</p>
<pre class="r"><code># Barplot with 10000 values drawn from the 
#  Poisson distribution with lambda = 3
ggplot(NULL, aes(x = rpois(10000, 3))) +
    geom_bar()</code></pre>
<p><img src="10E-Poisson_regression_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<pre class="r"><code># Probability of y = 1 if lambda = 3
dpois(1, 3)</code></pre>
<pre><code>## [1] 0.1493612</code></pre>
</div>
<div id="comparison-with-the-binomial-distribution" class="section level2">
<h2>Comparison with the binomial distribution</h2>
<p>For the binomial distribution, we had a positive or negative response for each individual (or sample unit) and we were trying to predict the probability of a positive response <span class="math inline">\(p\)</span>.</p>
<p>In the Poisson distribution, the response is the number of observations per sample unit and we try to predict the mean of that number.</p>
<p>If we have a binomial response that is rare at the individual level (<span class="math inline">\(p\)</span> is small) and the population <span class="math inline">\(n\)</span> is large, then we can model the number of cases at the population level by a Poisson distribution with <span class="math inline">\(\lambda = np\)</span>.</p>
<p><strong>Example</strong>: We are studying a birch forest where chaga is present on a small proportion (e.g. ~ 1%) of trees. Instead of counting birch trees affected and unaffected by the chaga, one could only count the number of chaga conks in plots of a given size and model that number with a Poisson distribution.</p>
</div>
<div id="comparison-with-the-normal-distribution" class="section level2">
<h2>Comparison with the normal distribution</h2>
<p>When <span class="math inline">\(\lambda\)</span> is large enough, the Poisson distribution becomes more symmetrical and approaches a normal distribution.</p>
<p><img src="10E-Poisson_regression_files/figure-html/unnamed-chunk-2-1.png" width="576" /></p>
<p>In other words, if the mean is large enough, the number of observations behaves almost like a continuous variable following a normal distribution with <span class="math inline">\(\mu = \lambda\)</span>.</p>
<p>In that case, the linear regression model could apply. However, keep in mind that each model makes different assumptions about the variance of the response. In the linear regression model, the mean <span class="math inline">\(\mu\)</span> depends on the predictors, but the variance <span class="math inline">\(\sigma^2\)</span> is constant. In the Poisson regression model, the mean and the variance depend on the predictors, because they are both equal to <span class="math inline">\(\lambda\)</span>. Diagnostic plots can tell you which model is the most appropriate.</p>
</div>
<div id="independence-of-observations-and-overdispersion" class="section level2">
<h2>Independence of observations and overdispersion</h2>
<p>As mentioned above, the Poisson distribution assumes the independence of individual observations. It is rare that this condition is perfectly respected in nature. For example:</p>
<ul>
<li>the probability of seeing a seedling of one species increases near other seedlings (agglomeration) if the seeds are dispersed in groups near the parent;</li>
<li>the observation of a species on a plot affects the likelihood of observing others based on competition or facilitation relationships between these species.</li>
</ul>
<p>Failure to meet the assumptions of the Poisson distribution can lead to <strong>overdispersion</strong> of observations, i.e., more extreme values are observed than predicted by the Poisson model. In the first example above, agglomeration results in more plots with 0 seedlings and more plots with a large number of seedlings.</p>
<p>In the graph below, the bars in red follow a Poisson distribution while the bars in blue represent a case of overdispersion. The mean of <span class="math inline">\(y\)</span> is 5 in both cases.</p>
<p><img src="10E-Poisson_regression_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>We will see later how to identify and address cases of overdispersion.</p>
</div>
</div>
<div id="poisson-regression" class="section level1">
<h1>Poisson regression</h1>
<p>Poisson regression is a generalized linear model where the response <span class="math inline">\(y\)</span> follows a Poisson distribution:</p>
<p><span class="math display">\[ y \sim Pois(\lambda) \]</span></p>
<p>Since <span class="math inline">\(\lambda\)</span> must be a positive number, we use the log function as a link with the linear predictor.</p>
<p><span class="math display">\[ \log{\lambda} = \eta = \beta_0 + \sum_{i = 1}^m \beta_i x_i \]</span></p>
<p>According to the properties of the log function, a value of 0 of the predictor <span class="math inline">\(\eta\)</span> corresponds to <span class="math inline">\(\lambda = 1\)</span>, a positive value corresponds to <span class="math inline">\(\lambda &gt; 1\)</span> and a negative value to <span class="math inline">\(\lambda &lt; 1\)</span>.</p>
<p><img src="10E-Poisson_regression_files/figure-html/unnamed-chunk-4-1.png" width="384" /></p>
<p>By inverting the log, we obtain a exponential relationship between the mean of the response (<span class="math inline">\(\lambda\)</span>) and the predictors:</p>
<p><span class="math display">\[ \hat{y} = \lambda = e^{\beta_0 + \sum_{i = 1}^m \beta_i x_i} \]</span></p>
<p>Since adding exponents is equivalent to a multiplication, this model corresponds to multiplicative effects of the predictors on the response.</p>
<p><span class="math display">\[ \hat{y} = e^{\beta_0} e^{\beta_1 x_1} e^{\beta_2 x_2} \ldots \]</span></p>
<p>The logarithm is the default link function for Poisson regression. To properly interpret the results of the regression, remember that a logarithmic transformation is applied to the mean response.</p>
<div id="summary-of-the-generalized-linear-models-seen-in-this-course" class="section level2">
<h2>Summary of the generalized linear models seen in this course</h2>
<table>
<colgroup>
<col width="12%" />
<col width="25%" />
<col width="30%" />
<col width="30%" />
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th>Distribution</th>
<th>Default link</th>
<th>Inverse link</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Linear regression</td>
<td>Normal: <span class="math inline">\(y \sim N(\mu, \sigma)\)</span></td>
<td>Identity: <span class="math inline">\(\mu = \eta\)</span></td>
<td><span class="math inline">\(\mu = \eta\)</span></td>
</tr>
<tr class="even">
<td>Logistic regression</td>
<td>Binomial: <span class="math inline">\(y \sim B(n, p)\)</span></td>
<td>Logit: <span class="math inline">\(\log(p/(1-p)) = \eta\)</span></td>
<td><span class="math inline">\(p = 1/(1+e^{-\eta})\)</span></td>
</tr>
<tr class="odd">
<td>Poisson regression</td>
<td>Poisson: <span class="math inline">\(y \sim Pois(\lambda)\)</span></td>
<td>Log: <span class="math inline">\(\log(\lambda) = \eta\)</span></td>
<td><span class="math inline">\(\lambda = e^{\eta}\)</span></td>
</tr>
</tbody>
</table>
</div>
<div id="example" class="section level2">
<h2>Example</h2>
<p>The <a href="../donnees/species.csv">species.csv</a> dataset shows the number of species of plants in different quadrats according to the total biomass in the quadrat, and soil pH coded on a three-level scale (low, mid, high).</p>
<pre class="r"><code>sp &lt;- read.csv(&quot;../donnees/species.csv&quot;) 
# Niveaux de pH dans le bon ordre
sp$pH &lt;- factor(sp$pH, levels = c(&quot;low&quot;, &quot;mid&quot;, &quot;high&quot;))
str(sp)</code></pre>
<pre><code>## &#39;data.frame&#39;:    90 obs. of  3 variables:
##  $ pH     : Factor w/ 3 levels &quot;low&quot;,&quot;mid&quot;,&quot;high&quot;: 3 3 3 3 3 3 3 3 3 3 ...
##  $ Biomass: num  0.469 1.731 2.09 3.926 4.367 ...
##  $ Species: int  30 39 44 35 25 29 23 18 19 12 ...</code></pre>
<p>Let’s look at the distribution of the response according to the predictors:</p>
<pre class="r"><code>ggplot(sp, aes(x = Biomass, y = Species)) +
    geom_point()</code></pre>
<p><img src="10E-Poisson_regression_files/figure-html/unnamed-chunk-6-1.png" width="384" /></p>
<pre class="r"><code>ggplot(sp, aes(x = pH, y = Species)) +
    geom_boxplot()</code></pre>
<p><img src="10E-Poisson_regression_files/figure-html/unnamed-chunk-6-2.png" width="384" /></p>
<p>On these graphs, we notice that the conditions associated with a larger mean number of species (low biomass, high pH) also have greater variance. This suggests that a Poisson regression might be appropriate.</p>
<p>As with logistic regression, Poisson regression uses the <code>glm</code> function. You must specify the <code>poisson</code> family and (optionally) the log link.</p>
<pre class="r"><code>mod_sp &lt;- glm(Species ~ Biomass + pH, sp, family = poisson(link = &quot;log&quot;))
summary(mod_sp)</code></pre>
<pre><code>## 
## Call:
## glm(formula = Species ~ Biomass + pH, family = poisson(link = &quot;log&quot;), 
##     data = sp)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.5959  -0.6989  -0.0737   0.6647   3.5604  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  2.71255    0.05713   47.48   &lt;2e-16 ***
## Biomass     -0.12756    0.01014  -12.58   &lt;2e-16 ***
## pHmid        0.69123    0.06815   10.14   &lt;2e-16 ***
## pHhigh       1.13639    0.06720   16.91   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 452.346  on 89  degrees of freedom
## Residual deviance:  99.242  on 86  degrees of freedom
## AIC: 526.43
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>Before interpreting the coefficients, let’s verify the model fit using diagnostic plots.</p>
<p><img src="10E-Poisson_regression_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>The first graph shows a trend in residuals (more negative at the extremes and more positive at the center). Given the number of points, this trend is probably not due to chance but represents a systematic effect that is not taken into account in this model.</p>
<p>So let’s try a more complex model where there is interaction between the effect of biomass and pH.</p>
<pre class="r"><code>mod_sp_inter &lt;- glm(Species ~ Biomass * pH, sp, family = poisson)</code></pre>
<p><img src="10E-Poisson_regression_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>Without having completely eliminated the trend, this fit seems much better.</p>
<p><strong>Note</strong>: In this case, these residuals approach normality, according to the quantile-quantile plot, because the observed values of the response are quite high (mean number of 20 species per quadrat). We had the same situation for binomial logistic regression when <span class="math inline">\(n\)</span> was high. However, we do not expect the quantile-quantile plot to show a straight line if <span class="math inline">\(\lambda\)</span> is small, even if the Poisson model applies perfectly.</p>
<p>Now let’s look at the model summary.</p>
<pre class="r"><code>summary(mod_sp_inter)</code></pre>
<pre><code>## 
## Call:
## glm(formula = Species ~ Biomass * pH, family = poisson, data = sp)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.4978  -0.7485  -0.0402   0.5575   3.2297  
## 
## Coefficients:
##                Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)     2.95255    0.08240  35.833  &lt; 2e-16 ***
## Biomass        -0.26216    0.03803  -6.893 5.47e-12 ***
## pHmid           0.48411    0.10723   4.515 6.34e-06 ***
## pHhigh          0.81557    0.10284   7.931 2.18e-15 ***
## Biomass:pHmid   0.12314    0.04270   2.884 0.003927 ** 
## Biomass:pHhigh  0.15503    0.04003   3.873 0.000108 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 452.346  on 89  degrees of freedom
## Residual deviance:  83.201  on 84  degrees of freedom
## AIC: 514.39
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>The AIC for this model is 514 compared to 526 for the no-interaction model, which confirms the better fit. The pseudo-<span class="math inline">\(R^2\)</span> is also high (1 - 83/452 = 0.82).</p>
<p>Here is a graph showing the superposition of the expected values of the response (curves plotted from <code>fitted(mod_sp_inter)</code>) and observed values (points) as a function of biomass and pH.</p>
<pre class="r"><code>ggplot(sp, aes(x = Biomass, y = Species, color = pH)) +
    geom_point() +
    geom_line(aes(y = fitted(mod_sp_inter))) +
    scale_color_brewer(palette = &quot;Dark2&quot;)</code></pre>
<p><img src="10E-Poisson_regression_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
</div>
<div id="interpretation-of-coefficients" class="section level2">
<h2>Interpretation of coefficients</h2>
<p>The interpretation of the model coefficients is more complex with the interactions, so let’s start with the model without interaction.</p>
<pre class="r"><code>summary(mod_sp)</code></pre>
<pre><code>## 
## Call:
## glm(formula = Species ~ Biomass + pH, family = poisson(link = &quot;log&quot;), 
##     data = sp)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.5959  -0.6989  -0.0737   0.6647   3.5604  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  2.71255    0.05713   47.48   &lt;2e-16 ***
## Biomass     -0.12756    0.01014  -12.58   &lt;2e-16 ***
## pHmid        0.69123    0.06815   10.14   &lt;2e-16 ***
## pHhigh       1.13639    0.06720   16.91   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 452.346  on 89  degrees of freedom
## Residual deviance:  99.242  on 86  degrees of freedom
## AIC: 526.43
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>It is easier to first determine the effect of each coefficient of the model on the linear predictor: <span class="math inline">\(\eta = \beta_0 + \sum_{i = 1}^{m} \beta_i x_i\)</span>, then deduce the effect on the mean response (<span class="math inline">\(\lambda\)</span>) from the function <span class="math inline">\(\lambda = e^{\eta}\)</span>.</p>
<p>For example, the intercept indicates that in the case where the biomass is 0 and the pH is low (reference level), <span class="math inline">\(\eta = 2.71\)</span> and therefore <span class="math inline">\(\lambda = e^{\eta} = 15.0\)</span>. Of course, this value is not realistic because there can be no species without biomass.</p>
<p>For other parameters:</p>
<ul>
<li><p>The <code>Biomass</code> coefficient indicates that <span class="math inline">\(\eta\)</span> decreases by 0.13 for each increase of one unit of biomass, if the other variables (i.e. the pH) remain constant. An additive change of -0.13 on the logarithmic scale corresponds to a multiplicative change of <span class="math inline">\(e^{-0.13} = 0.88\)</span>, a loss of 12% of the mean number of species per additional biomass unit.</p></li>
<li><p>The coefficient of <code>pHmid</code> indicates that when going from a low pH to a medium pH (for the same biomass), <span class="math inline">\(\eta\)</span> increases by 0.69. Since <span class="math inline">\(e^{0.69} = 2.0\)</span>, the mean number of species at an medium pH is twice that at a low pH.</p></li>
<li><p>Similarly, the coefficient of <code>pHhigh</code> indicates that the mean number of species is multiplied by <span class="math inline">\(e^{1.14} = 3.13\)</span> if we go from a low pH to a high pH for the same biomass.</p></li>
</ul>
<p>In summary, in the case where there are no interactions, the effects are additive on the linear predictor scale. The <span class="math inline">\(\beta_i\)</span> coefficient of the variable <span class="math inline">\(x_i\)</span> indicates that an increase of 1 unit of <span class="math inline">\(x_i\)</span>, while keeping the other variables constant, results in a <em>multiplication</em> of the mean response by <span class="math inline">\(e^{\beta_i}\)</span>.</p>
<p>Let’s look now at the case of the interaction:</p>
<pre class="r"><code>summary(mod_sp_inter)</code></pre>
<pre><code>## 
## Call:
## glm(formula = Species ~ Biomass * pH, family = poisson, data = sp)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.4978  -0.7485  -0.0402   0.5575   3.2297  
## 
## Coefficients:
##                Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)     2.95255    0.08240  35.833  &lt; 2e-16 ***
## Biomass        -0.26216    0.03803  -6.893 5.47e-12 ***
## pHmid           0.48411    0.10723   4.515 6.34e-06 ***
## pHhigh          0.81557    0.10284   7.931 2.18e-15 ***
## Biomass:pHmid   0.12314    0.04270   2.884 0.003927 ** 
## Biomass:pHhigh  0.15503    0.04003   3.873 0.000108 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 452.346  on 89  degrees of freedom
## Residual deviance:  83.201  on 84  degrees of freedom
## AIC: 514.39
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>In the model with interaction, the effect of pH depends on the biomass and vice versa. So let’s consider the three pH levels separately; for simplicity, the effect “biomass = 0” will be indicated even if it is not a realistic level of the variable.</p>
<ul>
<li><p>At low pH we have: <span class="math inline">\(\eta = 2.95 - 0.26 \times \text{biomass}\)</span>. Therefore, the mean number of species is <span class="math inline">\(e^{2.95} = 19\)</span> for a biomass of 0 and decreases by 23% (<span class="math inline">\(e^{-0.26} = 0.77\)</span>) per unit of biomass.</p></li>
<li><p>At medium pH, we have: <span class="math inline">\(\eta = (2.95 + 0.48) + (-0.26 + 0.12) \times \text{biomass}\)</span>, or <span class="math inline">\(\eta = 3.43 - 0.14 \times \text{biomass}\)</span>. Therefore, the mean number of species is 30.9 for a biomass of 0 and decreases by 13% per unit of biomass.</p></li>
<li><p>At high pH, we have: <span class="math inline">\(\eta = (2.95 + 0.82) + (-0.26 + 0.16) \times \text{biomass}\)</span>, equivalent to an mean number of species of 43.4 for a biomass of 0 and a 10% decrease per unit of biomass.</p></li>
</ul>
<p>For an interaction between a numeric variable and a categorical variable, it is easier to describe the effects for each level of the categorical variable, as we just did. For an interaction between two numeric variables, we can visualize the effects from the fitted value curves, but it becomes difficult to interpret the individual coefficients.</p>
</div>
</div>
<div id="overdispersion" class="section level1">
<h1>Overdispersion</h1>
<p>The summary of the Poisson regression results in the previous section included the message: <code>(Dispersion parameter for poisson family taken to be 1)</code>. This message reminds us that the variance of the observations is not estimated independently in this model (unlike the linear regression model), but is equal to the mean value <span class="math inline">\(\lambda\)</span> estimated according to the predictors at each point.</p>
<p>As mentioned in the introduction, the non-independence of individual observations may overdisperse the data with respect to the assumptions of the Poisson distribution. This overdispersion is represented by a parameter <span class="math inline">\(\phi\)</span> which multiplies the expected variance: for a mean <span class="math inline">\(\lambda\)</span>, the variance becomes <span class="math inline">\(\phi \lambda\)</span>.</p>
<p>Less frequently, it happens that <span class="math inline">\(\phi &lt; 1\)</span>, corresponding to <em>underdispersion</em> of the observations. Unlike overdispersion, where observations tend to be clustered (e.g., a few quadrats with many individuals, and many with few or no individuals), underdispersion means that observations are distributed more evenly than expected. This could be due, for example, to intraspecific competition or territoriality (in the case of animals) which leads individuals to space themselves at regular intervals.</p>
<div id="estimation-of-the-dispersion-parameter" class="section level2">
<h2>Estimation of the dispersion parameter</h2>
<p>To detect this overdispersion or under-dispersion, we will use the <span class="math inline">\(\chi^2\)</span> statistic, which we saw before in the context of contingency tables. This statistic is calculated from the square deviations between the observed (<span class="math inline">\(y\)</span>) and expected (<span class="math inline">\(\hat{y}\)</span>) values of the response, normalized by the expected value, for each of the <span class="math inline">\(n\)</span> points in the dataset.</p>
<p><span class="math display">\[ \chi^2 = \sum_{k=1}^n \frac{(y_k - \hat{y_k})^2}{\hat{y_k}} \]</span></p>
<p>If the data follow the Poisson distribution, the mean value of <span class="math inline">\(\chi^2\)</span> is equal to the number of residual degrees of freedom of the model: <span class="math inline">\(df_{res} = n - p\)</span>, where <span class="math inline">\(p\)</span> is the number of estimated parameters. To estimate the dispersion parameter <span class="math inline">\(\phi\)</span>, we will use the estimator:</p>
<p><span class="math display">\[ \hat{c} = \frac{\chi^2}{df_{res}} \]</span></p>
<p>For the model with interactions, we obtain almost exactly the theoretical value of 1:</p>
<pre class="r"><code>chisq &lt;- sum((sp$Species - fitted(mod_sp_inter))^2/fitted(mod_sp_inter))
chisq/mod_sp_inter$df.residual</code></pre>
<pre><code>## [1] 0.9970014</code></pre>
<p>For the model without interaction, we detect a small overdispersion.</p>
<pre class="r"><code>chisq &lt;- sum((sp$Species - fitted(mod_sp))^2/fitted(mod_sp))
chisq/mod_sp$df.residual</code></pre>
<pre><code>## [1] 1.10675</code></pre>
<p>To determine if the <span class="math inline">\(\chi^2\)</span> differs significantly from the expected value according to the Poisson distribution, we can calculate the probability of obtaining a higher <span class="math inline">\(\chi^2\)</span> if the model is correct.</p>
<pre class="r"><code>1 - pchisq(chisq, df = mod_sp$df.residual)</code></pre>
<pre><code>## [1] 0.2336238</code></pre>
<p>In this case, the overdispersion is not significant, so it is not necessary to adjust the results of the model.</p>
</div>
<div id="overdispersed-data-example" class="section level2">
<h2>Overdispersed data example</h2>
<p>The <a href="../donnees/galapagos.csv">galapagos.csv</a> dataset gives the number of plant species (<code>Species</code>) and the number of endemic species (<code>Endemics</code>) for different islands in the Galapagos according to their area, their mean elevation, the area of the nearest island (<code>Adjacent</code>), the distance to the nearest island (<code>Nearest</code>) and the distance to Santa Cruz island (<code>Scruz</code>).</p>
<pre class="r"><code>glp &lt;- read.csv(&quot;../donnees/galapagos.csv&quot;)
str(glp)</code></pre>
<pre><code>## &#39;data.frame&#39;:    30 obs. of  8 variables:
##  $ Name     : chr  &quot;Baltra&quot; &quot;Bartolome&quot; &quot;Caldwell&quot; &quot;Champion&quot; ...
##  $ Species  : int  58 31 3 25 2 18 24 10 8 2 ...
##  $ Endemics : int  23 21 3 9 1 11 0 7 4 2 ...
##  $ Area     : num  25.09 1.24 0.21 0.1 0.05 ...
##  $ Elevation: int  346 109 114 46 77 119 93 168 71 112 ...
##  $ Nearest  : num  0.6 0.6 2.8 1.9 1.9 8 6 34.1 0.4 2.6 ...
##  $ Scruz    : num  0.6 26.3 58.7 47.4 1.9 ...
##  $ Adjacent : num  1.84 572.33 0.78 0.18 903.82 ...</code></pre>
<p>Suppose we want to determine how the number of endemic plant species (those present on a single island) varies according to the predictors <code>Area</code>, <code>Elevation</code>, <code>Nearest</code> and <code>Adjacent</code>. Since each of these predictors is distributed very asymmetrically (see the example below for area), we will use the logarithm of each predictor.</p>
<p><img src="10E-Poisson_regression_files/figure-html/unnamed-chunk-19-1.png" width="576" /></p>
<p>We fit the following model in R. Note that the response is <code>Endemics</code> and not <code>log(Endemics)</code>, because the log link is included in the <code>glm</code> model with Poisson distribution.</p>
<pre class="r"><code>mod_glp &lt;- glm(Endemics ~ log(Area) + log(Elevation) + log(Nearest) + log(Adjacent), 
               data = glp, family = poisson)</code></pre>
<p>Diagnostic graphs indicate the presence of some extreme values, although none of Cook’s distances are &gt;1.</p>
<pre class="r"><code>par(mfrow = c(2,2))
plot(mod_glp)</code></pre>
<p><img src="10E-Poisson_regression_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<pre class="r"><code>par(mfrow = c(1, 1))</code></pre>
<p>The model indicates significant effects for 3 parameters: the number of endemic species increases with the area of the island; it decreases with distance to the nearest island and the area of that nearest island.</p>
<pre class="r"><code>summary(mod_glp)</code></pre>
<pre><code>## 
## Call:
## glm(formula = Endemics ~ log(Area) + log(Elevation) + log(Nearest) + 
##     log(Adjacent), family = poisson, data = glp)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -3.4411  -1.7215   0.0330   0.7395   3.8476  
## 
## Coefficients:
##                Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)     2.47684    0.45817   5.406 6.45e-08 ***
## log(Area)       0.27504    0.02922   9.414  &lt; 2e-16 ***
## log(Elevation)  0.01251    0.09251   0.135  0.89243    
## log(Nearest)   -0.06128    0.02118  -2.894  0.00381 ** 
## log(Adjacent)  -0.04576    0.01099  -4.162 3.15e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 743.55  on 29  degrees of freedom
## Residual deviance:  95.66  on 25  degrees of freedom
## AIC: 238.61
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>However, when testing the <span class="math inline">\(\chi^2\)</span>, we note that the data is overdispersed.</p>
<pre class="r"><code>chisq &lt;- sum((glp$Endemics - fitted(mod_glp))^2/fitted(mod_glp))
1 - pchisq(chisq, df = mod_glp$df.residual)</code></pre>
<pre><code>## [1] 1.109039e-09</code></pre>
<pre class="r"><code>disp &lt;- chisq/mod_glp$df.residual
disp</code></pre>
<pre><code>## [1] 3.700441</code></pre>
<p>The estimate of the dispersion parameter is 3.7. When <span class="math inline">\(\hat{c}\)</span> is not too high (typically, we suggest <span class="math inline">\(\hat{c} &lt; 4\)</span>), the Poisson regression coefficient estimates remain valid, but we need to multiply their standard errors by <span class="math inline">\(\sqrt{\hat{c}}\)</span>. In other words, overdispersion does not introduce bias, but increases the uncertainty over the values of the coefficients. If the overdispersion is very large, it is better to use another model.</p>
<p>To correct the standard errors, just add a <code>dispersion</code> argument when calling the <code>summary</code> function:</p>
<pre class="r"><code>summary(mod_glp, dispersion = disp)</code></pre>
<pre><code>## 
## Call:
## glm(formula = Endemics ~ log(Area) + log(Elevation) + log(Nearest) + 
##     log(Adjacent), family = poisson, data = glp)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -3.4411  -1.7215   0.0330   0.7395   3.8476  
## 
## Coefficients:
##                Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)     2.47684    0.88137   2.810  0.00495 ** 
## log(Area)       0.27504    0.05620   4.894 9.89e-07 ***
## log(Elevation)  0.01251    0.17796   0.070  0.94396    
## log(Nearest)   -0.06128    0.04074  -1.504  0.13251    
## log(Adjacent)  -0.04576    0.02115  -2.164  0.03049 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 3.700441)
## 
##     Null deviance: 743.55  on 29  degrees of freedom
## Residual deviance:  95.66  on 25  degrees of freedom
## AIC: 238.61
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>Equivalently, the <code>quasipoisson</code> family can be used to automatically estimate the dispersion parameter.</p>
<pre class="r"><code>mod_quasi &lt;- glm(Endemics ~ log(Area) + log(Elevation) + log(Nearest) + log(Adjacent), 
               data = glp, family = quasipoisson)
summary(mod_quasi)</code></pre>
<pre><code>## 
## Call:
## glm(formula = Endemics ~ log(Area) + log(Elevation) + log(Nearest) + 
##     log(Adjacent), family = quasipoisson, data = glp)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -3.4411  -1.7215   0.0330   0.7395   3.8476  
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     2.47684    0.88137   2.810  0.00948 ** 
## log(Area)       0.27504    0.05620   4.894 4.91e-05 ***
## log(Elevation)  0.01251    0.17796   0.070  0.94451    
## log(Nearest)   -0.06128    0.04074  -1.504  0.14504    
## log(Adjacent)  -0.04576    0.02115  -2.164  0.04025 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for quasipoisson family taken to be 3.700441)
## 
##     Null deviance: 743.55  on 29  degrees of freedom
## Residual deviance:  95.66  on 25  degrees of freedom
## AIC: NA
## 
## Number of Fisher Scoring iterations: 5</code></pre>
</div>
<div id="dispersion-parameter-for-the-binomial-family" class="section level2">
<h2>Dispersion parameter for the binomial family</h2>
<p>For a regression where the response is binomial (number of successes <span class="math inline">\(y\)</span> and failures <span class="math inline">\(n - y\)</span>), it can also be overdispersed or underdispersed. In this case, the dispersion parameter is estimated in the same way with the <span class="math inline">\(\chi^2\)</span> statistic. You can also use the <code>quasibinomial</code> family with the<code>glm</code> function.</p>
<p>For a binary response (0 or 1), the concept of dispersion parameter does not apply because the variance is always <span class="math inline">\(p(1-p)\)</span>.</p>
</div>
<div id="model-selection-with-overdispersion" class="section level2">
<h2>Model selection with overdispersion</h2>
<p>In addition to increasing the standard error of the model coefficients, overdispersion also affects model selection with the AIC. QAIC, the equivalent of the AIC for quasibinomial or quasipoisson type models, is calculated by dividing the first term of the AIC by the estimate of the dispersion parameter.</p>
<p><span class="math display">\[ QAIC = -\frac{2 \log L}{\hat{c}} + 2 K \]</span></p>
<p>Similarly, we can modify the AICc to obtain the QAICc.</p>
<p><span class="math display">\[ QAICc = -\frac{2 \log L}{\hat{c}} + 2 K \left( \frac{n}{n-K-1} \right) \]</span></p>
<p>The <span class="math inline">\(\hat{c}\)</span> itself counts as an estimated parameter, so the value of <span class="math inline">\(K\)</span> also increases by 1 compared to the model without overdispersion.</p>
<p>If we compare several models with the QAIC or QIACc, we must use a single value of <span class="math inline">\(\hat{c}\)</span>, the one calculated from the most complex model. This value is supplied to the <em>AICcmodavg</em> package functions (for example, <code>aictab</code>) with the <code>c.hat</code> argument.</p>
<p>For example, consider the following four models to predict the number of endemic species on the Galapagos Islands.</p>
<pre class="r"><code>mod_area &lt;- glm(Endemics ~ log(Area), data = glp, family = poisson)
mod_area_near &lt;- glm(Endemics ~ log(Area) + log(Nearest), data = glp, family = poisson)
mod_area_adj &lt;- glm(Endemics ~ log(Area) + log(Adjacent), data = glp, family = poisson)
mod_comp &lt;- glm(Endemics ~ log(Area) + log(Nearest) + log(Adjacent), data = glp, family = poisson)</code></pre>
<p>Note that we use the <code>poisson</code> family rather than <code>quasipoisson</code>; we will let the model selection function apply the correction. The dispersion parameter of the complete model can be calculated with the <code>c_hat</code> function of <em>AICcmodavg</em>. (This value differs a bit from the one above because we have removed the <code>Elevation</code> predictor.)</p>
<pre class="r"><code>library(AICcmodavg)

disp &lt;- c_hat(mod_comp)
disp</code></pre>
<pre><code>## &#39;c-hat&#39; 3.56 (method: pearson estimator)</code></pre>
<p>Here is the QAICc table for these models:</p>
<pre class="r"><code>mod_list &lt;- list(mod_area = mod_area, mod_area_near = mod_area_near, 
                 mod_area_adj = mod_area_adj, mod_comp = mod_comp)
aictab(mod_list, c.hat = disp)</code></pre>
<pre><code>## 
## Model selection based on QAICc:
## (c-hat estimate = 3.562208)
## 
##               K QAICc Delta_QAICc QAICcWt Cum.Wt Quasi.LL
## mod_area_adj  4 76.19        0.00    0.42   0.42   -33.30
## mod_comp      5 76.68        0.49    0.33   0.75   -32.09
## mod_area      3 78.49        2.29    0.13   0.89   -35.78
## mod_area_near 4 78.82        2.63    0.11   1.00   -34.61</code></pre>
<p>Let’s now compare with the version obtained without accounting for overdispersion.</p>
<pre class="r"><code>aictab(mod_list)</code></pre>
<pre><code>## 
## Model selection based on AICc:
## 
##               K   AICc Delta_AICc AICcWt Cum.Wt      LL
## mod_comp      4 238.23       0.00   0.95   0.95 -114.31
## mod_area_adj  3 244.14       5.91   0.05   1.00 -118.61
## mod_area_near 3 253.50      15.27   0.00   1.00 -123.29
## mod_area      2 259.37      21.14   0.00   1.00 -127.46</code></pre>
<p>Not only does the overdispersion change the ranking of the models, but it decreases the difference between the models: the <span class="math inline">\(\Delta QAICc\)</span> are much closer together than the <span class="math inline">\(\Delta AICc\)</span>. The four models have a weight greater than 10% in the first case, while the first model gets 95% of the weight in the second table. Thus, there is more uncertainty about which model is best.</p>
</div>
</div>
<div id="summary" class="section level1">
<h1>Summary</h1>
<div id="poisson-regression-1" class="section level2">
<h2>Poisson regression</h2>
<ul>
<li><p>The Poisson distribution represents the number of independent observations of an event in a sampling interval.</p></li>
<li><p>The Poisson regression model is based on a Poisson distribution of the response around its mean value; this value is related to the linear predictor by the logarithm function.</p></li>
<li><p>Because of the logarithmic relationship, the additive effects on the linear predictor scale become multiplicative effects on the scale of the response.</p></li>
<li><p>The binomial and Poisson distributions assume a certain relationship between the mean value of the response and its variance. Overdispersion occurs when the variance is larger than expected by the distribution.</p></li>
<li><p>If the dispersion parameter is not too high (<span class="math inline">\(\hat{c} &lt; 4\)</span>), we can still use the Poisson (or binomial) model and multiply the standard errors of the coefficients by <span class="math inline">\(\sqrt{\hat{c}}\)</span>. For model selection, the AIC(c) must be replaced by the QAIC(c) to account for overdispersion.</p></li>
</ul>
</div>
<div id="statistical-modeling-general-points-to-remember" class="section level2">
<h2>Statistical modeling: general points to remember</h2>
<p>We studied different types of models this semester (ANOVA, linear regression, generalized linear models and mixed models in the next classes). You may have noticed that we apply similar steps in each case.</p>
<ul>
<li>Explore the data (look at the distribution of individual variables and correlations);</li>
<li>Choose a model type and fit it (<code>lm</code>, <code>glm</code>, etc.);</li>
<li>Verify the model assumptions (e.g. diagnostic graphs, dispersion parameter);</li>
<li>Interpret the estimated values of the coefficients;</li>
<li>Visualize model predictions;</li>
<li>If several candidate models: compare the fit, select the best model or make average predictions from multiple models.</li>
</ul>
<p>You should be able to complete each of its steps for the statistical models seen in this course and those that you will apply to your research.</p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
